const estruturas = [
  {
    numero: "1",
    raioCalculado: "53 pm",
    raioCovalente: "31 pm",
    raioVanDerWaals: "120 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "0.2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.0002 GPa",
    moduloYoung: "0.001 GPa",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "1",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "H₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "2",
    raioCalculado: "31 pm",
    raioCovalente: "28 pm",
    raioVanDerWaals: "140 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.0033 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "He",
    pontoTransicao: "N/A"
  },
  {
    numero: "3",
    raioCalculado: "167 pm",
    raioCovalente: "128 pm",
    raioVanDerWaals: "182 pm",
    raioIonico: "90 pm (+1)",
    durezaBrinell: "5 MPa",
    durezaMohs: "0.6",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "11 GPa",
    moduloYoung: "4.9 GPa",
    moduloCisalhamento: "4.2 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Li",
    pontoTransicao: "N/A"
  },
  {
    numero: "4",
    raioCalculado: "112 pm",
    raioCovalente: "96 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "45 pm (+2)",
    durezaBrinell: "490 MPa",
    durezaMohs: "5.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "75 GPa",
    moduloYoung: "287 GPa",
    moduloCisalhamento: "132 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "6",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Be",
    pontoTransicao: "N/A"
  },
  {
    numero: "5",
    raioCalculado: "87 pm",
    raioCovalente: "84 pm",
    raioVanDerWaals: "192 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "9.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "224 GPa",
    moduloYoung: "393 GPa",
    moduloCisalhamento: "168 GPa",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "B",
    pontoTransicao: "N/A"
  },
  {
    numero: "6",
    raioCalculado: "67 pm",
    raioCovalente: "76 pm",
    raioVanDerWaals: "170 pm",
    raioIonico: "16 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "10",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "442 GPa",
    moduloYoung: "1050 GPa",
    moduloCisalhamento: "478 GPa",
    estruturaCristalina: "Hexagonal / Cúbica",
    numeroCoordenacao: "4",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "C",
    pontoTransicao: "N/A"
  },
  {
    numero: "7",
    raioCalculado: "56 pm",
    raioCovalente: "71 pm",
    raioVanDerWaals: "155 pm",
    raioIonico: "146 pm (–3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "1.9 GPa",
    moduloYoung: "0.25 GPa",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Molecular",
    numeroCoordenacao: "3",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "N₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "8",
    raioCalculado: "48 pm",
    raioCovalente: "66 pm",
    raioVanDerWaals: "152 pm",
    raioIonico: "140 pm (–2)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.001 GPa",
    moduloYoung: "0.002 GPa",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Molecular",
    numeroCoordenacao: "2",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "O₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "9",
    raioCalculado: "42 pm",
    raioCovalente: "57 pm",
    raioVanDerWaals: "147 pm",
    raioIonico: "133 pm (–1)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.5 GPa",
    moduloYoung: "0.07 GPa",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Molecular",
    numeroCoordenacao: "1",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "F₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "10",
    raioCalculado: "38 pm",
    raioCovalente: "58 pm",
    raioVanDerWaals: "154 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.4 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ne",
    pontoTransicao: "N/A"
  },
  {
    numero: "11",
    raioCalculado: "190 pm",
    raioCovalente: "166 pm",
    raioVanDerWaals: "227 pm",
    raioIonico: "102 pm (+1)",
    durezaBrinell: "0.69 MPa",
    durezaMohs: "0.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "6.3 GPa",
    moduloYoung: "10 GPa",
    moduloCisalhamento: "3.3 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Na",
    pontoTransicao: "N/A"
  },
  {
    numero: "12",
    raioCalculado: "145 pm",
    raioCovalente: "141 pm",
    raioVanDerWaals: "173 pm",
    raioIonico: "72 pm (+2)",
    durezaBrinell: "260 MPa",
    durezaMohs: "2.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "35 GPa",
    moduloYoung: "45 GPa",
    moduloCisalhamento: "17 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "6",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Mg",
    pontoTransicao: "N/A"
  },
  {
    numero: "13",
    raioCalculado: "118 pm",
    raioCovalente: "121 pm",
    raioVanDerWaals: "184 pm",
    raioIonico: "53.5 pm (+3)",
    durezaBrinell: "245 MPa",
    durezaMohs: "2.75",
    durezaVickers: "167 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "76 GPa",
    moduloYoung: "70 GPa",
    moduloCisalhamento: "26 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Al",
    pontoTransicao: "N/A"
  },
  {
    numero: "14",
    raioCalculado: "111 pm",
    raioCovalente: "111 pm",
    raioVanDerWaals: "210 pm",
    raioIonico: "41 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "6.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "97.6 GPa",
    moduloYoung: "130 GPa",
    moduloCisalhamento: "79.9 GPa",
    estruturaCristalina: "Diamante cúbico",
    numeroCoordenacao: "4",
    empacotamentoAtômico: "34%",
    estruturaMolecular: "Si",
    pontoTransicao: "N/A"
  },
  {
    numero: "15",
    raioCalculado: "98 pm",
    raioCovalente: "107 pm",
    raioVanDerWaals: "180 pm",
    raioIonico: "38 pm (+5)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "7 GPa",
    moduloYoung: "44.2 GPa",
    moduloCisalhamento: "18.6 GPa",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "3",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "P₄",
    pontoTransicao: "N/A"
  },
  {
    numero: "16",
    raioCalculado: "88 pm",
    raioCovalente: "105 pm",
    raioVanDerWaals: "180 pm",
    raioIonico: "184 pm (–2)",
    durezaBrinell: "N/A",
    durezaMohs: "2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "7.7 GPa",
    moduloYoung: "25 GPa",
    moduloCisalhamento: "7 GPa",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "2",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "S₈",
    pontoTransicao: "N/A"
  },
    {
    numero: "17",
    raioCalculado: "79 pm",
    raioCovalente: "99 pm",
    raioVanDerWaals: "175 pm",
    raioIonico: "181 pm (–1)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "1",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Cl₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "18",
    raioCalculado: "71 pm",
    raioCovalente: "96 pm",
    raioVanDerWaals: "188 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "0.0033 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ar",
    pontoTransicao: "N/A"
  },
  {
    numero: "19",
    raioCalculado: "243 pm",
    raioCovalente: "203 pm",
    raioVanDerWaals: "275 pm",
    raioIonico: "138 pm (+1)",
    durezaBrinell: "0.363 MPa",
    durezaMohs: "0.4",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "3.1 GPa",
    moduloYoung: "13 GPa",
    moduloCisalhamento: "5.5 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "K",
    pontoTransicao: "N/A"
  },
  {
    numero: "20",
    raioCalculado: "194 pm",
    raioCovalente: "176 pm",
    raioVanDerWaals: "231 pm",
    raioIonico: "100 pm (+2)",
    durezaBrinell: "167 MPa",
    durezaMohs: "1.75",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "17 GPa",
    moduloYoung: "20 GPa",
    moduloCisalhamento: "7.4 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Ca",
    pontoTransicao: "N/A"
  },
  {
    numero: "21",
    raioCalculado: "184 pm",
    raioCovalente: "170 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "74.5 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "5.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "57 GPa",
    moduloYoung: "74 GPa",
    moduloCisalhamento: "29 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Sc",
    pontoTransicao: "N/A"
  },
  {
    numero: "22",
    raioCalculado: "176 pm",
    raioCovalente: "160 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "61 pm (+4)",
    durezaBrinell: "716 MPa",
    durezaMohs: "6",
    durezaVickers: "970 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "116 GPa",
    moduloYoung: "116 GPa",
    moduloCisalhamento: "44 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Ti",
    pontoTransicao: "N/A"
  },
  {
    numero: "23",
    raioCalculado: "171 pm",
    raioCovalente: "153 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "59 pm (+5)",
    durezaBrinell: "628 MPa",
    durezaMohs: "7",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "160 GPa",
    moduloYoung: "128 GPa",
    moduloCisalhamento: "47 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "V",
    pontoTransicao: "N/A"
  },
  {
    numero: "24",
    raioCalculado: "166 pm",
    raioCovalente: "139 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "52 pm (+6)",
    durezaBrinell: "1120 MPa",
    durezaMohs: "8.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "160 GPa",
    moduloYoung: "279 GPa",
    moduloCisalhamento: "115 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Cr",
    pontoTransicao: "N/A"
  },
  {
    numero: "25",
    raioCalculado: "161 pm",
    raioCovalente: "161 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "46 pm (+7)",
    durezaBrinell: "196 MPa",
    durezaMohs: "6",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "120 GPa",
    moduloYoung: "198 GPa",
    moduloCisalhamento: "80 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Mn",
    pontoTransicao: "N/A"
  },
  {
    numero: "26",
    raioCalculado: "156 pm",
    raioCovalente: "126 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "65 pm (+2)",
    durezaBrinell: "490 MPa",
    durezaMohs: "4",
    durezaVickers: "608 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "170 GPa",
    moduloYoung: "211 GPa",
    moduloCisalhamento: "82 GPa",
    estruturaCristalina: "Cúbica centrada no corpo",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Fe",
    pontoTransicao: "N/A"
  },
  {
    numero: "27",
    raioCalculado: "152 pm",
    raioCovalente: "125 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "63 pm (+2)",
    durezaBrinell: "700 MPa",
    durezaMohs: "5",
    durezaVickers: "1043 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "180 GPa",
    moduloYoung: "209 GPa",
    moduloCisalhamento: "75 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Co",
    pontoTransicao: "N/A"
  },
  {
    numero: "28",
    raioCalculado: "149 pm",
    raioCovalente: "124 pm",
    raioVanDerWaals: "163 pm",
    raioIonico: "69 pm (+2)",
    durezaBrinell: "700 MPa",
    durezaMohs: "4",
    durezaVickers: "638 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "180 GPa",
    moduloYoung: "200 GPa",
    moduloCisalhamento: "76 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Ni",
    pontoTransicao: "N/A"
  },
    {
    numero: "29",
    raioCalculado: "145 pm",
    raioCovalente: "132 pm",
    raioVanDerWaals: "140 pm",
    raioIonico: "77 pm (+1)",
    durezaBrinell: "874 MPa",
    durezaMohs: "3",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "140 GPa",
    moduloYoung: "110 GPa",
    moduloCisalhamento: "48 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Cu",
    pontoTransicao: "N/A"
  },
  {
    numero: "30",
    raioCalculado: "142 pm",
    raioCovalente: "122 pm",
    raioVanDerWaals: "139 pm",
    raioIonico: "74 pm (+2)",
    durezaBrinell: "327 MPa",
    durezaMohs: "2.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "70 GPa",
    moduloYoung: "108 GPa",
    moduloCisalhamento: "43 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Zn",
    pontoTransicao: "N/A"
  },
  {
    numero: "31",
    raioCalculado: "136 pm",
    raioCovalente: "122 pm",
    raioVanDerWaals: "187 pm",
    raioIonico: "62 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "1.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ga",
    pontoTransicao: "N/A"
  },
  {
    numero: "32",
    raioCalculado: "125 pm",
    raioCovalente: "122 pm",
    raioVanDerWaals: "211 pm",
    raioIonico: "73 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "6",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ge",
    pontoTransicao: "N/A"
  },
  {
    numero: "33",
    raioCalculado: "114 pm",
    raioCovalente: "121 pm",
    raioVanDerWaals: "185 pm",
    raioIonico: "58 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "3.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "As",
    pontoTransicao: "N/A"
  },
  {
    numero: "34",
    raioCalculado: "103 pm",
    raioCovalente: "116 pm",
    raioVanDerWaals: "190 pm",
    raioIonico: "198 pm (–2)",
    durezaBrinell: "N/A",
    durezaMohs: "2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Se",
    pontoTransicao: "N/A"
  },
  {
    numero: "35",
    raioCalculado: "94 pm",
    raioCovalente: "114 pm",
    raioVanDerWaals: "185 pm",
    raioIonico: "196 pm (–1)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Br₂",
    pontoTransicao: "N/A"
  },
  {
    numero: "36",
    raioCalculado: "88 pm",
    raioCovalente: "110 pm",
    raioVanDerWaals: "202 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Kr",
    pontoTransicao: "N/A"
  },
   {
    numero: "37",
    raioCalculado: "265 pm",
    raioCovalente: "220 pm",
    raioVanDerWaals: "303 pm",
    raioIonico: "152 pm (+1)",
    durezaBrinell: "0.216 MPa",
    durezaMohs: "0.3",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "2.5 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Rb",
    pontoTransicao: "N/A"
  },
  {
    numero: "38",
    raioCalculado: "219 pm",
    raioCovalente: "195 pm",
    raioVanDerWaals: "249 pm",
    raioIonico: "118 pm (+2)",
    durezaBrinell: "N/A",
    durezaMohs: "1.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Sr",
    pontoTransicao: "N/A"
  },
  {
    numero: "39",
    raioCalculado: "212 pm",
    raioCovalente: "180 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "90 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Y",
    pontoTransicao: "N/A"
  },
  {
    numero: "40",
    raioCalculado: "206 pm",
    raioCovalente: "155 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "86 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Zr",
    pontoTransicao: "N/A"
  },
  {
    numero: "41",
    raioCalculado: "198 pm",
    raioCovalente: "145 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "78 pm (+5)",
    durezaBrinell: "N/A",
    durezaMohs: "6",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Nb",
    pontoTransicao: "N/A"
  },
  {
    numero: "42",
    raioCalculado: "190 pm",
    raioCovalente: "145 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "69 pm (+6)",
    durezaBrinell: "N/A",
    durezaMohs: "5.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Mo",
    pontoTransicao: "N/A"
  },
  {
    numero: "43",
    raioCalculado: "183 pm",
    raioCovalente: "135 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Tc",
    pontoTransicao: "N/A"
  },
  {
    numero: "44",
    raioCalculado: "178 pm",
    raioCovalente: "130 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "68 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "6.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ru",
    pontoTransicao: "N/A"
  },
  {
    numero: "45",
    raioCalculado: "173 pm",
    raioCovalente: "135 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "67 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "6",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Rh",
    pontoTransicao: "N/A"
  },
  {
    numero: "46",
    raioCalculado: "169 pm",
    raioCovalente: "140 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "86 pm (+2)",
    durezaBrinell: "N/A",
    durezaMohs: "4.75",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Pd",
    pontoTransicao: "N/A"
  },
  {
    numero: "47",
    raioCalculado: "165 pm",
    raioCovalente: "145 pm",
    raioVanDerWaals: "172 pm",
    raioIonico: "129 pm (+1)",
    durezaBrinell: "24.5 MPa",
    durezaMohs: "2.5",
    durezaVickers: "251 MPa",
    durezaRockwell: "N/A",
    moduloBulk: "100 GPa",
    moduloYoung: "83 GPa",
    moduloCisalhamento: "30 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Ag",
    pontoTransicao: "N/A"
  },
  {
    numero: "48",
    raioCalculado: "161 pm",
    raioCovalente: "144 pm",
    raioVanDerWaals: "158 pm",
    raioIonico: "95 pm (+2)",
    durezaBrinell: "203 MPa",
    durezaMohs: "2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "46 GPa",
    moduloYoung: "50 GPa",
    moduloCisalhamento: "19 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Cd",
    pontoTransicao: "N/A"
  },
  {
  numero: "49",
  raioCalculado: "156 pm",
  raioCovalente: "142 pm",
  raioVanDerWaals: "193 pm",
  raioIonico: "80 pm (+3)",
  durezaBrinell: "8.8 MPa",
  durezaMohs: "1.2",
  durezaVickers: "N/A",
  durezaRockwell: "N/A",
  moduloBulk: "N/A",
  moduloYoung: "N/A",
  moduloCisalhamento: "N/A",
  estruturaCristalina: "Tetragonal",
  numeroCoordenacao: "N/A",
  empacotamentoAtômico: "N/A",
  estruturaMolecular: "In",
  pontoTransicao: "N/A"
    },
    {
    numero: "50",
    raioCalculado: "145 pm",
    raioCovalente: "139 pm",
    raioVanDerWaals: "217 pm",
    raioIonico: "93 pm (+4)",
    durezaBrinell: "51.0 MPa",
    durezaMohs: "1.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "58 GPa",
    moduloYoung: "50 GPa",
    moduloCisalhamento: "18 GPa",
    estruturaCristalina: "Tetragonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Sn",
    pontoTransicao: "N/A"
    },
    {
    numero: "51",
    raioCalculado: "145 pm",
    raioCovalente: "139 pm",
    raioVanDerWaals: "206 pm",
    raioIonico: "76 pm (+5)",
    durezaBrinell: "294 MPa",
    durezaMohs: "2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "42 GPa",
    moduloYoung: "40 GPa",
    moduloCisalhamento: "16 GPa",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Sb",
    pontoTransicao: "N/A"
    },
    {
    numero: "52",
    raioCalculado: "140 pm",
    raioCovalente: "138 pm",
    raioVanDerWaals: "206 pm",
    raioIonico: "70 pm (+6)",
    durezaBrinell: "N/A",
    durezaMohs: "2.3",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Te",
    pontoTransicao: "N/A"
    },
    {
    numero: "53",
    raioCalculado: "133 pm",
    raioCovalente: "139 pm",
    raioVanDerWaals: "198 pm",
    raioIonico: "220 pm (−1)",
    durezaBrinell: "N/A",
    durezaMohs: "0.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Ortorrômbica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "I₂",
    pontoTransicao: "N/A"
    },
    {
    numero: "54",
    raioCalculado: "108 pm",
    raioCovalente: "140 pm",
    raioVanDerWaals: "216 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "3.6 MPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Xe",
    pontoTransicao: "N/A"
    },
    {
    numero: "55",
    raioCalculado: "298 pm",
    raioCovalente: "235 pm",
    raioVanDerWaals: "343 pm",
    raioIonico: "167 pm (+1)",
    durezaBrinell: "N/A",
    durezaMohs: "0.2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "1.6 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Cs",
    pontoTransicao: "N/A"
    },
    {
    numero: "56",
    raioCalculado: "253 pm",
    raioCovalente: "198 pm",
    raioVanDerWaals: "268 pm",
    raioIonico: "135 pm (+2)",
    durezaBrinell: "N/A",
    durezaMohs: "1.25",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "13 GPa",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Ba",
    pontoTransicao: "N/A"
    },
    {
    numero: "72",
    raioCalculado: "159 pm",
    raioCovalente: "144 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "78 pm (+4)",
    durezaBrinell: "1700 MPa",
    durezaMohs: "5.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "109 GPa",
    moduloYoung: "78 GPa",
    moduloCisalhamento: "30 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Hf",
    pontoTransicao: "N/A"
    },
    {
    numero: "73",
    raioCalculado: "146 pm",
    raioCovalente: "134 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "68 pm (+5)",
    durezaBrinell: "800 MPa",
    durezaMohs: "6.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "200 GPa",
    moduloYoung: "186 GPa",
    moduloCisalhamento: "69 GPa",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "Ta",
    pontoTransicao: "N/A"
    },
    {
    numero: "74",
    raioCalculado: "139 pm",
    raioCovalente: "130 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "62 pm (+6)",
    durezaBrinell: "3500 MPa",
    durezaMohs: "7.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "310 GPa",
    moduloYoung: "411 GPa",
    moduloCisalhamento: "161 GPa",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "8",
    empacotamentoAtômico: "68%",
    estruturaMolecular: "W",
    pontoTransicao: "N/A"
    },
    {
    numero: "75",
    raioCalculado: "137 pm",
    raioCovalente: "128 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "63 pm (+7)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Re",
    pontoTransicao: "N/A"
    },
    {
    numero: "76",
    raioCalculado: "135 pm",
    raioCovalente: "127 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "63 pm (+4)",
    durezaBrinell: "N/A",
    durezaMohs: "7",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Os",
    pontoTransicao: "N/A"
    },
    {
    numero: "77",
    raioCalculado: "136 pm",
    raioCovalente: "125 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "68 pm (+3)",
    durezaBrinell: "1670 MPa",
    durezaMohs: "6.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "320 GPa",
    moduloYoung: "528 GPa",
    moduloCisalhamento: "210 GPa",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Ir",
    pontoTransicao: "N/A"
    },
    {
    numero: "78",
    raioCalculado: "139 pm",
    raioCovalente: "128 pm",
    raioVanDerWaals: "175 pm",
    raioIonico: "86 pm (+2)",
    durezaBrinell: "392 MPa",
    durezaMohs: "4.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "230 GPa",
    moduloYoung: "168 GPa",
    moduloCisalhamento: "61 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Pt",
    pontoTransicao: "N/A"
    },
    {
    numero: "79",
    raioCalculado: "144 pm",
    raioCovalente: "136 pm",
    raioVanDerWaals: "166 pm",
    raioIonico: "137 pm (+1)",
    durezaBrinell: "245 MPa",
    durezaMohs: "2.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "180 GPa",
    moduloYoung: "79 GPa",
    moduloCisalhamento: "27 GPa",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "12",
    empacotamentoAtômico: "74%",
    estruturaMolecular: "Au",
    pontoTransicao: "N/A"
    },
    {
    numero: "80",
    raioCalculado: "151 pm",
    raioCovalente: "132 pm",
    raioVanDerWaals: "155 pm",
    raioIonico: "119 pm (+1)",
    durezaBrinell: "N/A",
    durezaMohs: "1.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "25 GPa",
    moduloYoung: "25 GPa",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Hg",
    pontoTransicao: "N/A"
    },
    {
    numero: "81",
    raioCalculado: "156 pm",
    raioCovalente: "145 pm",
    raioVanDerWaals: "196 pm",
    raioIonico: "150 pm (+1)",
    durezaBrinell: "N/A",
    durezaMohs: "1.2",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Tetragonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Tl",
    pontoTransicao: "N/A"
    },
    {
    numero: "82",
    raioCalculado: "154 pm",
    raioCovalente: "146 pm",
    raioVanDerWaals: "202 pm",
    raioIonico: "119 pm (+2)",
    durezaBrinell: "38 MPa",
    durezaMohs: "1.5",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "46 GPa",
    moduloYoung: "16 GPa",
    moduloCisalhamento: "5.6 GPa",
    estruturaCristalina: "Tetragonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Pb",
    pontoTransicao: "N/A"
    },
    {
    numero: "83",
    raioCalculado: "143 pm",
    raioCovalente: "148 pm",
    raioVanDerWaals: "207 pm",
    raioIonico: "103 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "2.25",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "31 GPa",
    moduloYoung: "32 GPa",
    moduloCisalhamento: "12 GPa",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Bi",
    pontoTransicao: "N/A"
    },
    {
    numero: "84",
    raioCalculado: "135 pm",
    raioCovalente: "140 pm",
    raioVanDerWaals: "197 pm",
    raioIonico: "100 pm (+2)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Romboédrica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Po",
    pontoTransicao: "N/A"
    },
    {
    numero: "85",
    raioCalculado: "127 pm",
    raioCovalente: "150 pm",
    raioVanDerWaals: "202 pm",
    raioIonico: "133 pm (-1)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Ortorômbica",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "At",
    pontoTransicao: "N/A"
    },
    {
    numero: "86",
    raioCalculado: "120 pm",
    raioCovalente: "150 pm",
    raioVanDerWaals: "220 pm",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Rn",
    pontoTransicao: "N/A"
    },
    {
    numero: "87",
    raioCalculado: "N/A",
    raioCovalente: "180 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "148 pm (+1)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de corpo centrado",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Fr",
    pontoTransicao: "N/A"
    },
    {
    numero: "88",
    raioCalculado: "215 pm",
    raioCovalente: "207 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "148 pm (+2)",
    durezaBrinell: "N/A",
    durezaMohs: "0.9",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ra",
    pontoTransicao: "N/A"
    },
    {
    numero: "104",
    raioCalculado: "200 pm",
    raioCovalente: "157 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Rf",
    pontoTransicao: "N/A"
    },
    {
    numero: "105",
    raioCalculado: "200 pm",
    raioCovalente: "149 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Db",
    pontoTransicao: "N/A"
    },
    {
    numero: "106",
    raioCalculado: "185 pm",
    raioCovalente: "143 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Sg",
    pontoTransicao: "N/A"
    },
    {
    numero: "107",
    raioCalculado: "185 pm",
    raioCovalente: "141 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Bh",
    pontoTransicao: "N/A"
    },
    {
    numero: "108",
    raioCalculado: "185 pm",
    raioCovalente: "134 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Hs",
    pontoTransicao: "N/A"
    },
    {
    numero: "109",
    raioCalculado: "185 pm",
    raioCovalente: "129 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Mt",
    pontoTransicao: "N/A"
    },
    {
    numero: "110",
    raioCalculado: "185 pm",
    raioCovalente: "128 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ds",
    pontoTransicao: "N/A"
    },
    {
    numero: "111",
    raioCalculado: "185 pm",
    raioCovalente: "121 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Rg",
    pontoTransicao: "N/A"
    },
    {
    numero: "112",
    raioCalculado: "N/A",
    raioCovalente: "122 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Cn",
    pontoTransicao: "N/A"
    },
    {
    numero: "113",
    raioCalculado: "N/A",
    raioCovalente: "136 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Desconhecida",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Nh",
    pontoTransicao: "N/A"
    },
    {
    numero: "114",
    raioCalculado: "N/A",
    raioCovalente: "143 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Cúbica de face centrada (prevista)",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Fl",
    pontoTransicao: "N/A"
    },
    {
    numero: "115",
    raioCalculado: "N/A",
    raioCovalente: "162 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Desconhecida",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Mc",
    pontoTransicao: "N/A"
    },
    {
    numero: "116",
    raioCalculado: "N/A",
    raioCovalente: "175 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Desconhecida",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Lv",
    pontoTransicao: "N/A"
    },
    {
    numero: "117",
    raioCalculado: "N/A",
    raioCovalente: "165 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Desconhecida",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Ts",
    pontoTransicao: "N/A"
    },
    {
    numero: "118",
    raioCalculado: "N/A",
    raioCovalente: "N/A",
    raioVanDerWaals: "N/A",
    raioIonico: "N/A",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Prevista: Cúbica de face centrada",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "N/A",
    estruturaMolecular: "Og",
    pontoTransicao: "N/A"
    },
    {
  numero: "57",
  raioCalculado: "165 pm",
  raioCovalente: "195 pm",
  raioVanDerWaals: "N/A",
  raioIonico: "106 pm (+3)",
  durezaBrinell: "N/A",
  durezaMohs: "N/A",
  durezaVickers: "N/A",
  durezaRockwell: "N/A",
  moduloBulk: "N/A",
  moduloYoung: "N/A",
  moduloCisalhamento: "N/A",
  estruturaCristalina: "Hexagonal",
  numeroCoordenacao: "N/A",
  empacotamentoAtômico: "Cúbico de face centrada",
  estruturaMolecular: "La",
  pontoTransicao: "N/A"
    },
    {
    numero: "58",
    raioCalculado: "160 pm",
    raioCovalente: "198 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Ce",
    pontoTransicao: "N/A"
    },
    {
    numero: "59",
    raioCalculado: "155 pm",
    raioCovalente: "199 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Pr",
    pontoTransicao: "N/A"
    },
    {
    numero: "60",
    raioCalculado: "152 pm",
    raioCovalente: "200 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Nd",
    pontoTransicao: "N/A"
    },
    {
    numero: "61",
    raioCalculado: "148 pm",
    raioCovalente: "202 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Pm",
    pontoTransicao: "N/A"
    },
    {
    numero: "62",
    raioCalculado: "144 pm",
    raioCovalente: "205 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Sm",
    pontoTransicao: "N/A"
    },
    {
    numero: "63",
    raioCalculado: "141 pm",
    raioCovalente: "208 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Eu",
    pontoTransicao: "N/A"
    },
    {
    numero: "64",
    raioCalculado: "138 pm",
    raioCovalente: "211 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Gd",
    pontoTransicao: "N/A"
    },
    {
    numero: "65",
    raioCalculado: "135 pm",
    raioCovalente: "213 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Tb",
    pontoTransicao: "N/A"
    },
    {
    numero: "66",
    raioCalculado: "132 pm",
    raioCovalente: "216 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Dy",
    pontoTransicao: "N/A"
    },
    {
    numero: "67",
    raioCalculado: "130 pm",
    raioCovalente: "219 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Ho",
    pontoTransicao: "N/A"
    },
    {
    numero: "68",
    raioCalculado: "127 pm",
    raioCovalente: "222 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Er",
    pontoTransicao: "N/A"
    },
    {
    numero: "69",
    raioCalculado: "125 pm",
    raioCovalente: "224 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Tm",
    pontoTransicao: "N/A"
    },
    {
    numero: "70",
    raioCalculado: "123 pm",
    raioCovalente: "227 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Yb",
    pontoTransicao: "N/A"
    },
    {
    numero: "71",
    raioCalculado: "121 pm",
    raioCovalente: "229 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Lu",
    pontoTransicao: "N/A"
    },
    {
    numero: "89",
    raioCalculado: "175 pm",
    raioCovalente: "180 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Ac",
    pontoTransicao: "N/A"
    },
    {
    numero: "90",
    raioCalculado: "175 pm",
    raioCovalente: "190 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Th",
    pontoTransicao: "N/A"
    },
    {
    numero: "91",
    raioCalculado: "175 pm",
    raioCovalente: "195 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Pa",
    pontoTransicao: "N/A"
    },
    {
    numero: "92",
    raioCalculado: "175 pm",
    raioCovalente: "200 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "U",
    pontoTransicao: "N/A"
    },
    {
    numero: "93",
    raioCalculado: "175 pm",
    raioCovalente: "205 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Np",
    pontoTransicao: "N/A"
    },
    {
    numero: "94",
    raioCalculado: "175 pm",
    raioCovalente: "210 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Pu",
    pontoTransicao: "N/A"
    },
    {
    numero: "95",
    raioCalculado: "175 pm",
    raioCovalente: "215 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Am",
    pontoTransicao: "N/A"
    },
    {
    numero: "96",
    raioCalculado: "175 pm",
    raioCovalente: "220 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Cm",
    pontoTransicao: "N/A"
    },
    {
    numero: "97",
    raioCalculado: "175 pm",
    raioCovalente: "225 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Bk",
    pontoTransicao: "N/A"
    },
    {
    numero: "98",
    raioCalculado: "175 pm",
    raioCovalente: "230 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Cf",
    pontoTransicao: "N/A"
    },
    {
    numero: "99",
    raioCalculado: "175 pm",
    raioCovalente: "235 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Es",
    pontoTransicao: "N/A"
    },
    {
    numero: "100",
    raioCalculado: "175 pm",
    raioCovalente: "240 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Fm",
    pontoTransicao: "N/A"
    },
    {
    numero: "101",
    raioCalculado: "175 pm",
    raioCovalente: "245 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Md",
    pontoTransicao: "N/A"
    },
    {
    numero: "102",
    raioCalculado: "175 pm",
    raioCovalente: "250 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "No",
    pontoTransicao: "N/A"
    },
    {
    numero: "103",
    raioCalculado: "175 pm",
    raioCovalente: "255 pm",
    raioVanDerWaals: "N/A",
    raioIonico: "106 pm (+3)",
    durezaBrinell: "N/A",
    durezaMohs: "N/A",
    durezaVickers: "N/A",
    durezaRockwell: "N/A",
    moduloBulk: "N/A",
    moduloYoung: "N/A",
    moduloCisalhamento: "N/A",
    estruturaCristalina: "Hexagonal",
    numeroCoordenacao: "N/A",
    empacotamentoAtômico: "Cúbico de face centrada",
    estruturaMolecular: "Lr",
    pontoTransicao: "N/A"
    },
];