const elementos = [
    {
      numero: "1",
      nome: "Hidrogênio",
      tipo: "Não metal",
      simbolo: "H",
      massa: "1.008",
      configuracao: "1s1",
      estado: "Gasoso",
      descobridor: "Henry Cavendish",
      descoberta: "1766",
      usos: "Produção de amônia, combustível",
      wikipedia: "https://pt.wikipedia.org/wiki/Hidrog%C3%AAnio",
      niveldeenergia: "1",
      densidadeSTP: "0.00008988 g/cm³",
      densidadeliquido: "0.0708 g/cm³",
      abundanciaUniverso: "75%",
      grupo: "1",
      periodo: "1",
      bloco: "s",
      cor: "#FFB5B5",
      origemNome: "Do grego 'hydro' e 'genes', que significa 'formador de água'",
      densidade: "0.08988 g/L",
      radioatividade: "Não",
    },
    {
      numero: "2",
      nome: "Hélio",
      tipo: "Gás nobre",
      simbolo: "He",
      massa: "4.0026",
      configuracao: "1s2",
      estado: "Gasoso",
      descobridor: "Pierre Janssen",
      descoberta: "1868",
      usos: "Balões, refrigeração",
      wikipedia: "https://pt.wikipedia.org/wiki/H%C3%A9lio",
      niveldeenergia: "1",
      densidadeSTP: "0.0001785 g/cm³",
      densidadeliquido: "0.125 g/cm³",
      abundanciaUniverso: "23%",
      grupo: "18",
      periodo: "1",
      bloco: "s",
      cor: "#FFD700",
      origemNome: "Do grego 'helios', que significa 'sol'",
      densidade: "0.1785 g/L",
      radioatividade: "Não",
    },
    {
      numero: "3",
      nome: "Lítio",
      tipo: "Metal alcalino",
      simbolo: "Li",
      massa: "6.94",
      configuracao: "[He] 2s1",
      estado: "Sólido",
      descobridor: "Johan August Arfwedson",
      descoberta: "1817",
      usos: "Baterias, cerâmica",
      wikipedia: "https://pt.wikipedia.org/wiki/L%C3%ADtio",
      niveldeenergia: "2",
      densidadeSTP: "0.534 g/cm³",
      densidadeliquido: "0.512 g/cm³",
      abundanciaUniverso: "0.0007%",
      grupo: "1",
      periodo: "2",
      bloco: "s",
      cor: "#CC80FF",
      origemNome: "Do grego 'lithos', que significa 'pedra'",
      densidade: "0.534 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "4",
      nome: "Berílio",
      tipo: "Metal alcalino-terroso",
      simbolo: "Be",
      massa: "9.0122",
      configuracao: "[He] 2s2",
      estado: "Sólido",
      descobridor: "Louis Nicolas Vauquelin",
      descoberta: "1798",
      usos: "Aeronáutica, ligas metálicas",
      wikipedia: "https://pt.wikipedia.org/wiki/Ber%C3%ADlio",
      niveldeenergia: "2",
      densidadeSTP: "1.85 g/cm³",
      densidadeliquido: "1.77 g/cm³",
      abundanciaUniverso: "0.0002%",
      grupo: "2",
      periodo: "2",
      bloco: "s",
      cor: "#C2FF00",
      origemNome: "Do grego 'beryllos', um tipo de pedra preciosa",
      densidade: "1.85 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "5",
      nome: "Boro",
      tipo: "Semi-metal",
      simbolo: "B",
      massa: "10.81",
      configuracao: "[He] 2s2 2p1",
      estado: "Sólido",
      descobridor: "Joseph Louis Gay-Lussac",
      descoberta: "1808",
      usos: "Vidros, detergentes",
      wikipedia: "https://pt.wikipedia.org/wiki/Boro",
      niveldeenergia: "2",
      densidadeSTP: "2.34 g/cm³",
      densidadeliquido: "N/A",
      abundanciaUniverso: "0.001%",
      grupo: "13",
      periodo: "2",
      bloco: "p",
      cor: "#FFB5B5",
      origemNome: "Do árabe 'buraq'",
      densidade: "2.34 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "6",
      nome: "Carbono",
      tipo: "Não metal",
      simbolo: "C",
      massa: "12.011",
      configuracao: "[He] 2s2 2p2",
      estado: "Sólido",
      descobridor: "Antiguidade",
      descoberta: "Antiguidade",
      usos: "Combustíveis, materiais orgânicos",
      wikipedia: "https://pt.wikipedia.org/wiki/Carbono",
      niveldeenergia: "2",
      densidadeSTP: "2.267 g/cm³",
      densidadeliquido: "N/A",
      abundanciaUniverso: "0.02%",
      grupo: "14",
      periodo: "2",
      bloco: "p",
      cor: "#909090",
      origemNome: "Do latim 'carbo', que significa carvão",
      densidade: "2.267 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "7",
      nome: "Nitrogênio",
      tipo: "Não metal",
      simbolo: "N",
      massa: "14.007",
      configuracao: "[He] 2s2 2p3",
      estado: "Gasoso",
      descobridor: "Daniel Rutherford",
      descoberta: "1772",
      usos: "Fertilizantes, explosivos",
      wikipedia: "https://pt.wikipedia.org/wiki/Nitrog%C3%AAnio",
      niveldeenergia: "2",
      densidadeSTP: "0.0012506 g/cm³",
      densidadeliquido: "0.808 g/cm³",
      abundanciaUniverso: "0.1%",
      grupo: "15",
      periodo: "2",
      bloco: "p",
      cor: "#3050F8",
      origemNome: "Do latim 'nitrum' e 'genes', que significa formador de nitro",
      densidade: "0.0012506 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "8",
      nome: "Oxigênio",
      tipo: "Não metal",
      simbolo: "O",
      massa: "15.999",
      configuracao: "[He] 2s2 2p4",
      estado: "Gasoso",
      descobridor: "Carl Wilhelm Scheele",
      descoberta: "1774",
      usos: "Respiração, combustão",
      wikipedia: "https://pt.wikipedia.org/wiki/Oxig%C3%AAnio",
      niveldeenergia: "2",
      densidadeSTP: "0.001429 g/cm³",
      densidadeliquido: "1.141 g/cm³",
      abundanciaUniverso: "0.1%",
      grupo: "16",
      periodo: "2",
      bloco: "p",
      cor: "#FF0D0D",
      origemNome: "Do grego 'oxys' e 'genes', que significa ácido formador",
      densidade: "0.001429 g/cm³",
      radioatividade: "Não",
    },
    {
      numero: "9",
      nome: "Flúor",
      tipo: "Halogênio",
      simbolo: "F",
      massa: "18.998",
      configuracao: "[He] 2s2 2p5",
      estado: "Gasoso",
      descobridor: "André-Marie Ampère",
      descoberta: "1886",
      usos: "Fluoretos, refrigerantes",
      wikipedia: "https://pt.wikipedia.org/wiki/Fl%C3%BAor",
      niveldeenergia: "2",
      densidadeSTP: "0.001696 g/cm³",
      densidadeliquido: "1.51 g/cm³",
      abundanciaUniverso: "0.0004%",
      grupo: "17",
      periodo: "2",
      bloco: "p",
      cor: "#90E050",
      origemNome: "Do latim 'fluere', que significa fluir",
      densidade: "0.001696 g/cm³",
    },
    {
      numero: "10",
      nome: "Neônio",
      tipo: "Gás nobre",
      simbolo: "Ne",
      massa: "20.180",
      configuracao: "[He] 2s2 2p6",
      estado: "Gasoso",
      descobridor: "Sir William Ramsay",
      descoberta: "1898",
      usos: "Iluminação, sinais luminosos",
      wikipedia: "https://pt.wikipedia.org/wiki/Ne%C3%B4nio",
      niveldeenergia: "2",
      densidadeSTP: "0.0008999 g/cm³",
      densidadeliquido: "1.207 g/cm³",
      abundanciaUniverso: "0.0018%",
      grupo: "18",
      periodo: "2",
      bloco: "p",
      cor: "#B3E3F5",
      origemNome: "Do grego 'neos', que significa novo",
      densidade: "0.0008999 g/cm³",
      radioatividade: "Não",
    },
    {
        numero: "11",
        nome: "Sódio",
        tipo: "Metal alcalino",
        simbolo: "Na",
        massa: "22.990",
        configuracao: "[Ne] 3s1",
        estado: "Sólido",
        descobridor: "Humphry Davy",
        descoberta: "1807",
        usos: "Sais, indústria química",
        wikipedia: "https://pt.wikipedia.org/wiki/S%C3%B3dio",
        niveldeenergia: "3",
        densidadeSTP: "0.971 g/cm³",
        densidadeliquido: "0.927 g/cm³",
        abundanciaUniverso: "0.002%",
        grupo: "1",
        periodo: "3",
        bloco: "s",
        cor: "#E6E6FA",
        origemNome: "Do latim 'soda', que significa 'substância alcalina'",
        densidade: "0.971 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "12",
        nome: "Magnésio",
        tipo: "Metal alcalino-terroso",
        simbolo: "Mg",
        massa: "24.305",
        configuracao: "[Ne] 3s2",
        estado: "Sólido",
        descobridor: "Joseph Black",
        descoberta: "1755",
        usos: "Ligas metálicas, alumínio",
        wikipedia: "https://pt.wikipedia.org/wiki/Magn%C3%A9sio",
        niveldeenergia: "3",
        densidadeSTP: "1.738 g/cm³",
        densidadeliquido: "1.578 g/cm³",
        abundanciaUniverso: "0.0004%",
        grupo: "2",
        periodo: "3",
        bloco: "s",
        cor: "#D1D1E0",
        origemNome: "Do grego 'magnesia', uma região da Grécia",
        densidade: "1.738 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "13",
        nome: "Alumínio",
        tipo: "Metal",
        simbolo: "Al",
        massa: "26.982",
        configuracao: "[Ne] 3s2 3p1",
        estado: "Sólido",
        descobridor: "Hans Christian Ørsted",
        descoberta: "1825",
        usos: "Ligas metálicas, embalagens",
        wikipedia: "https://pt.wikipedia.org/wiki/Alum%C3%ADnio",
        niveldeenergia: "3",
        densidadeSTP: "2.70 g/cm³",
        densidadeliquido: "2.375 g/cm³",
        abundanciaUniverso: "0.0008%",
        grupo: "13",
        periodo: "3",
        bloco: "p",
        cor: "#A9A9A9",
        origemNome: "Do latim 'alumen', que significa 'sal' ou 'alume'",
        densidade: "2.70 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "14",
        nome: "Silício",
        tipo: "Semi-metal",
        simbolo: "Si",
        massa: "28.085",
        configuracao: "[Ne] 3s2 3p2",
        estado: "Sólido",
        descobridor: "Jöns Jacob Berzelius",
        descoberta: "1824",
        usos: "Eletrônicos, semicondutores",
        wikipedia: "https://pt.wikipedia.org/wiki/Sil%C3%ADcio",
        niveldeenergia: "3",
        densidadeSTP: "2.33 g/cm³",
        densidadeliquido: "2.54 g/cm³",
        abundanciaUniverso: "0.0075%",
        grupo: "14",
        periodo: "3",
        bloco: "p",
        cor: "#B4B4B4",
        origemNome: "Do latim 'silex', que significa 'pedra dura'",
        densidade: "2.33 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "15",
        nome: "Fósforo",
        tipo: "Não metal",
        simbolo: "P",
        massa: "30.974",
        configuracao: "[Ne] 3s2 3p3",
        estado: "Sólido",
        descobridor: "Hennig Brand",
        descoberta: "1669",
        usos: "Fertilizantes, detergentes",
        wikipedia: "https://pt.wikipedia.org/wiki/F%C3%B3sforo",
        niveldeenergia: "3",
        densidadeSTP: "1.82 g/cm³",
        densidadeliquido: "1.83 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "15",
        periodo: "3",
        bloco: "p",
        cor: "#FF8000",
        origemNome: "Do grego 'phosphoros', que significa 'portador de luz'",
        densidade: "1.82 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "16",
        nome: "Enxofre",
        tipo: "Não metal",
        simbolo: "S",
        massa: "32.06",
        configuracao: "[Ne] 3s2 3p4",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Fertilizantes, ácido sulfúrico",
        wikipedia: "https://pt.wikipedia.org/wiki/Enxofre",
        niveldeenergia: "3",
        densidadeSTP: "2.07 g/cm³",
        densidadeliquido: "1.92 g/cm³",
        abundanciaUniverso: "0.0004%",
        grupo: "16",
        periodo: "3",
        bloco: "p",
        cor: "#FFFF00",
        origemNome: "Do latim 'sulphur', que significa 'enxofre'",
        densidade: "2.07 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "17",
        nome: "Cloro",
        tipo: "Halogênio",
        simbolo: "Cl",
        massa: "35.45",
        configuracao: "[Ne] 3s2 3p5",
        estado: "Gasoso",
        descobridor: "Carl Wilhelm Scheele",
        descoberta: "1774",
        usos: "Desinfetantes, indústria química",
        wikipedia: "https://pt.wikipedia.org/wiki/Cloro",
        niveldeenergia: "3",
        densidadeSTP: "0.003214 g/cm³",
        densidadeliquido: "0.00156 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "17",
        periodo: "3",
        bloco: "p",
        cor: "#3E4F60",
        origemNome: "Do grego 'khloros', que significa 'verde-amarelado'",
        densidade: "0.003214 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "18",
        nome: "Argônio",
        tipo: "Gás nobre",
        simbolo: "Ar",
        massa: "39.948",
        configuracao: "[Ne] 3s2 3p6",
        estado: "Gasoso",
        descobridor: "Lord Rayleigh e William Ramsay",
        descoberta: "1894",
        usos: "Iluminação, proteção de ambientes inertes",
        wikipedia: "https://pt.wikipedia.org/wiki/Arg%C3%B4nio",
        niveldeenergia: "3",
        densidadeSTP: "0.001784 g/cm³",
        densidadeliquido: "1.40 g/cm³",
        abundanciaUniverso: "0.0002%",
        grupo: "18",
        periodo: "3",
        bloco: "p",
        cor: "#80D1E3",
        origemNome: "Do grego 'argos', que significa 'inerte'",
        densidade: "0.001784 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "19",
        nome: "Potássio",
        tipo: "Metal alcalino",
        simbolo: "K",
        massa: "39.098",
        configuracao: "[Ar] 4s1",
        estado: "Sólido",
        descobridor: "Humphry Davy",
        descoberta: "1807",
        usos: "Fertilizantes, sabões",
        wikipedia: "https://pt.wikipedia.org/wiki/Pot%C3%A1ssio",
        niveldeenergia: "4",
        densidadeSTP: "0.862 g/cm³",
        densidadeliquido: "0.816 g/cm³",
        abundanciaUniverso: "0.0014%",
        grupo: "1",
        periodo: "4",
        bloco: "s",
        cor: "#D9D9D6",
        origemNome: "Do árabe 'al-qaly', que significa 'cinzas'",
        densidade: "0.862 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "20",
        nome: "Cálcio",
        tipo: "Metal alcalino-terroso",
        simbolo: "Ca",
        massa: "40.078",
        configuracao: "[Ar] 4s2",
        estado: "Sólido",
        descobridor: "Humphry Davy",
        descoberta: "1808",
        usos: "Cimento, construção civil",
        wikipedia: "https://pt.wikipedia.org/wiki/C%C3%A1lcio",
        niveldeenergia: "4",
        densidadeSTP: "1.54 g/cm³",
        densidadeliquido: "1.46 g/cm³",
        abundanciaUniverso: "0.002%",
        grupo: "2",
        periodo: "4",
        bloco: "s",
        cor: "#F2F2F2",
        origemNome: "Do latim 'calx', que significa 'cal' ou 'calcário'",
        densidade: "1.54 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "21",
        nome: "Escândio",
        tipo: "Metal de transição",
        simbolo: "Sc",
        massa: "44.956",
        configuracao: "[Ar] 3d1 4s2",
        estado: "Sólido",
        descobridor: "Lars Fredrik Nilson",
        descoberta: "1879",
        usos: "Liga metálica, alumínio",
        wikipedia: "https://pt.wikipedia.org/wiki/Esc%C3%A2ndio",
        niveldeenergia: "4",
        densidadeSTP: "2.985 g/cm³",
        densidadeliquido: "2.10 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "3",
        periodo: "4",
        bloco: "d",
        cor: "#D1D1D1",
        origemNome: "Do nome da Escandinávia",
        densidade: "2.985 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "22",
        nome: "Titânio",
        tipo: "Metal de transição",
        simbolo: "Ti",
        massa: "47.867",
        configuracao: "[Ar] 3d2 4s2",
        estado: "Sólido",
        descobridor: "William Gregor",
        descoberta: "1791",
        usos: "Indústria aeronáutica, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Tit%C3%A2nio",
        niveldeenergia: "4",
        densidadeSTP: "4.54 g/cm³",
        densidadeliquido: "4.17 g/cm³",
        abundanciaUniverso: "0.0004%",
        grupo: "4",
        periodo: "4",
        bloco: "d",
        cor: "#A0A0A0",
        origemNome: "Do titã da mitologia grega",
        densidade: "4.54 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "23",
        nome: "Vanádio",
        tipo: "Metal de transição",
        simbolo: "V",
        massa: "50.942",
        configuracao: "[Ar] 3d3 4s2",
        estado: "Sólido",
        descobridor: "Andrés Manuel del Río",
        descoberta: "1801",
        usos: "Aço, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Van%C3%A1dio",
        niveldeenergia: "4",
        densidadeSTP: "6.11 g/cm³",
        densidadeliquido: "5.5 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "5",
        periodo: "4",
        bloco: "d",
        cor: "#8A8A8A",
        origemNome: "Da deusa escandinava 'Vana'",
        densidade: "6.11 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "24",
        nome: "Cromo",
        tipo: "Metal de transição",
        simbolo: "Cr",
        massa: "52.00",
        configuracao: "[Ar] 3d5 4s1",
        estado: "Sólido",
        descobridor: "Louis Nicolas Vauquelin",
        descoberta: "1797",
        usos: "Ligas metálicas, revestimentos",
        wikipedia: "https://pt.wikipedia.org/wiki/Cromo",
        niveldeenergia: "4",
        densidadeSTP: "7.19 g/cm³",
        densidadeliquido: "6.9 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "6",
        periodo: "4",
        bloco: "d",
        cor: "#A3A3A3",
        origemNome: "Do grego 'chroma', que significa cor",
        densidade: "7.19 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "25",
        nome: "Manganês",
        tipo: "Metal de transição",
        simbolo: "Mn",
        massa: "54.938",
        configuracao: "[Ar] 3d5 4s2",
        estado: "Sólido",
        descobridor: "Johann Gottlieb",
        descoberta: "1774",
        usos: "Aço, baterias",
        wikipedia: "https://pt.wikipedia.org/wiki/Mangan%C3%AAse",
        niveldeenergia: "4",
        densidadeSTP: "7.43 g/cm³",
        densidadeliquido: "7.0 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "7",
        periodo: "4",
        bloco: "d",
        cor: "#FF4D4D",
        origemNome: "Do latim 'manganum', que significa 'ferro'",
        densidade: "7.43 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "26",
        nome: "Ferro",
        tipo: "Metal de transição",
        simbolo: "Fe",
        massa: "55.845",
        configuracao: "[Ar] 3d6 4s2",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Aço, indústrias",
        wikipedia: "https://pt.wikipedia.org/wiki/Ferro",
        niveldeenergia: "4",
        densidadeSTP: "7.87 g/cm³",
        densidadeliquido: "7.0 g/cm³",
        abundanciaUniverso: "0.1%",
        grupo: "8",
        periodo: "4",
        bloco: "d",
        cor: "#D6D6D6",
        origemNome: "Do latim 'ferrum'",
        densidade: "7.87 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "27",
        nome: "Cobalto",
        tipo: "Metal de transição",
        simbolo: "Co",
        massa: "58.933",
        configuracao: "[Ar] 3d7 4s2",
        estado: "Sólido",
        descobridor: "Georg Brandt",
        descoberta: "1735",
        usos: "Baterias, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Cobalto",
        niveldeenergia: "4",
        densidadeSTP: "8.90 g/cm³",
        densidadeliquido: "6.9 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "9",
        periodo: "4",
        bloco: "d",
        cor: "#4C4C80",
        origemNome: "Do alemão 'kobold', que significa 'duende'",
        densidade: "8.90 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "28",
        nome: "Níquel",
        tipo: "Metal de transição",
        simbolo: "Ni",
        massa: "58.693",
        configuracao: "[Ar] 3d8 4s2",
        estado: "Sólido",
        descobridor: "Axel Fredrik Cronstedt",
        descoberta: "1751",
        usos: "Ligas metálicas, baterias",
        wikipedia: "https://pt.wikipedia.org/wiki/N%C3%ADquel",
        niveldeenergia: "4",
        densidadeSTP: "8.90 g/cm³",
        densidadeliquido: "7.8 g/cm³",
        abundanciaUniverso: "0.0005%",
        grupo: "10",
        periodo: "4",
        bloco: "d",
        cor: "#8080BF",
        origemNome: "Do alemão 'kupfernickel', que significa 'cobre falso'",
        densidade: "8.90 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "29",
        nome: "Cobre",
        tipo: "Metal de transição",
        simbolo: "Cu",
        massa: "63.546",
        configuracao: "[Ar] 3d10 4s1",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Fiação elétrica, moedas",
        wikipedia: "https://pt.wikipedia.org/wiki/Cobre",
        niveldeenergia: "4",
        densidadeSTP: "8.92 g/cm³",
        densidadeliquido: "8.0 g/cm³",
        abundanciaUniverso: "0.0003%",
        grupo: "11",
        periodo: "4",
        bloco: "d",
        cor: "#E0A0A0",
        origemNome: "Do latim 'cuprum', que significa 'do chipre'",
        densidade: "8.92 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "30",
        nome: "Zinco",
        tipo: "Metal de transição",
        simbolo: "Zn",
        massa: "65.38",
        configuracao: "[Ar] 3d10 4s2",
        estado: "Sólido",
        descobridor: "Andreas Sigismund Marggraf",
        descoberta: "1746",
        usos: "Ligas metálicas, galvanização",
        wikipedia: "https://pt.wikipedia.org/wiki/Zinco",
        niveldeenergia: "4",
        densidadeSTP: "7.14 g/cm³",
        densidadeliquido: "6.57 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "12",
        periodo: "4",
        bloco: "d",
        cor: "#808080",
        origemNome: "Do alemão 'zinc', que significa 'zinc'",
        densidade: "7.14 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "31",
        nome: "Gálio",
        tipo: "Metal pobre",
        simbolo: "Ga",
        massa: "69.723",
        configuracao: "[Ar] 3d10 4s2 4p1",
        estado: "Sólido",
        descobridor: "Paul-Émile Lecoq de Boisbaudran",
        descoberta: "1875",
        usos: "Semicondutores, lâmpadas",
        wikipedia: "https://pt.wikipedia.org/wiki/G%C3%A1lio",
        niveldeenergia: "4",
        densidadeSTP: "5.91 g/cm³",
        densidadeliquido: "3.0 g/cm³",
        abundanciaUniverso: "0.0002%",
        grupo: "13",
        periodo: "4",
        bloco: "p",
        cor: "#A0A0A0",
        origemNome: "Do latim 'Gallia', que significa 'França'",
        densidade: "5.91 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "32",
        nome: "Germânio",
        tipo: "Semi-metal",
        simbolo: "Ge",
        massa: "72.63",
        configuracao: "[Ar] 3d10 4s2 4p2",
        estado: "Sólido",
        descobridor: "Clemens Winkler",
        descoberta: "1886",
        usos: "Semicondutores",
        wikipedia: "https://pt.wikipedia.org/wiki/Germ%C3%A2nio",
        niveldeenergia: "4",
        densidadeSTP: "5.32 g/cm³",
        densidadeliquido: "5.0 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "14",
        periodo: "4",
        bloco: "p",
        cor: "#A8A8A8",
        origemNome: "Do latim 'Germania', que significa 'Alemanha'",
        densidade: "5.32 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "33",
        nome: "Arsênio",
        tipo: "Semi-metal",
        simbolo: "As",
        massa: "74.922",
        configuracao: "[Ar] 3d10 4s2 4p3",
        estado: "Sólido",
        descobridor: "Albertus Magnus",
        descoberta: "1250",
        usos: "Pesticidas, semicondutores",
        wikipedia: "https://pt.wikipedia.org/wiki/Ars%C3%AAnio",
        niveldeenergia: "4",
        densidadeSTP: "5.72 g/cm³",
        densidadeliquido: "5.3 g/cm³",
        abundanciaUniverso: "0.0002%",
        grupo: "15",
        periodo: "4",
        bloco: "p",
        cor: "#B0B0D0",
        origemNome: "Do grego 'arsenikon', que significa 'poderoso'",
        densidade: "5.72 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "34",
        nome: "Selênio",
        tipo: "Não metal",
        simbolo: "Se",
        massa: "78.971",
        configuracao: "[Ar] 3d10 4s2 4p4",
        estado: "Sólido",
        descobridor: "Jöns Jacob Berzelius",
        descoberta: "1817",
        usos: "Eletrônicos, baterias solares",
        wikipedia: "https://pt.wikipedia.org/wiki/Sel%C3%AAnio",
        niveldeenergia: "4",
        densidadeSTP: "4.81 g/cm³",
        densidadeliquido: "4.8 g/cm³",
        abundanciaUniverso: "0.0002%",
        grupo: "16",
        periodo: "4",
        bloco: "p",
        cor: "#B0B0FF",
        origemNome: "Do grego 'selene', que significa 'lua'",
        densidade: "4.81 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "35",
        nome: "Bromo",
        tipo: "Halogênio",
        simbolo: "Br",
        massa: "79.904",
        configuracao: "[Ar] 3d10 4s2 4p5",
        estado: "Líquido",
        descobridor: "Antoine-Jérôme Balard",
        descoberta: "1826",
        usos: "Desinfetantes, pesticidas",
        wikipedia: "https://pt.wikipedia.org/wiki/Bromo",
        niveldeenergia: "4",
        densidadeSTP: "3.12 g/cm³",
        densidadeliquido: "3.1 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "17",
        periodo: "4",
        bloco: "p",
        cor: "#B07F7F",
        origemNome: "Do grego 'bromos', que significa 'fedor'",
        densidade: "3.12 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "36",
        nome: "Criptônio",
        tipo: "Gás nobre",
        simbolo: "Kr",
        massa: "83.798",
        configuracao: "[Ar] 3d10 4s2 4p6",
        estado: "Gasoso",
        descobridor: "William Ramsay e Morris Travers",
        descoberta: "1898",
        usos: "Iluminação, lasers",
        wikipedia: "https://pt.wikipedia.org/wiki/Cript%C3%B4nio",
        niveldeenergia: "4",
        densidadeSTP: "0.00375 g/cm³",
        densidadeliquido: "2.83 g/cm³",
        abundanciaUniverso: "0.0001%",
        grupo: "18",
        periodo: "4",
        bloco: "p",
        cor: "#9C9CFF",
        origemNome: "Do grego 'kryptos', que significa 'oculto'",
        densidade: "0.00375 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "37",
        nome: "Rubídio",
        tipo: "Metal alcalino",
        simbolo: "Rb",
        massa: "85.468",
        configuracao: "[Kr] 5s1",
        estado: "Sólido",
        descobridor: "Robert Bunsen e Gustav Kirchhoff",
        descoberta: "1861",
        usos: "Pesquisa, células de bateria",
        wikipedia: "https://pt.wikipedia.org/wiki/R%C3%BAbidio",
        niveldeenergia: "5",
        densidadeSTP: "1.53 g/cm³",
        densidadeliquido: "1.46 g/cm³",
        abundanciaUniverso: "0.00007%",
        grupo: "1",
        periodo: "5",
        bloco: "s",
        cor: "#E5A0A0",
        origemNome: "Do latim 'rubidus', que significa 'vermelho escuro'",
        densidade: "1.53 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "38",
        nome: "Estrôncio",
        tipo: "Metal alcalino-terroso",
        simbolo: "Sr",
        massa: "87.62",
        configuracao: "[Kr] 5s2",
        estado: "Sólido",
        descobridor: "William Cruickshank e Adair Crawford",
        descoberta: "1790",
        usos: "Fogos de artifício, ímãs",
        wikipedia: "https://pt.wikipedia.org/wiki/Estr%C3%B4ncio",
        niveldeenergia: "5",
        densidadeSTP: "2.64 g/cm³",
        densidadeliquido: "2.52 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "2",
        periodo: "5",
        bloco: "s",
        cor: "#F5A9A9",
        origemNome: "Do grego 'strontion', cidade na Escócia onde foi encontrado",
        densidade: "2.64 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "39",
        nome: "Yttrium",
        tipo: "Metal de transição",
        simbolo: "Y",
        massa: "88.905",
        configuracao: "[Kr] 4d1 5s2",
        estado: "Sólido",
        descobridor: "Johan Gadolin",
        descoberta: "1794",
        usos: "Lâmpadas, lasers",
        wikipedia: "https://pt.wikipedia.org/wiki/Yt%C3%ADrio",
        niveldeenergia: "5",
        densidadeSTP: "4.47 g/cm³",
        densidadeliquido: "4.12 g/cm³",
        abundanciaUniverso: "0.00007%",
        grupo: "3",
        periodo: "5",
        bloco: "d",
        cor: "#E5E5E5",
        origemNome: "De Ytterby, cidade na Suécia onde foi descoberto",
        densidade: "4.47 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "40",
        nome: "Zirconium",
        tipo: "Metal de transição",
        simbolo: "Zr",
        massa: "91.224",
        configuracao: "[Kr] 4d2 5s2",
        estado: "Sólido",
        descobridor: "Martin Heinrich Klaproth",
        descoberta: "1789",
        usos: "Indústria nuclear, joias",
        wikipedia: "https://pt.wikipedia.org/wiki/Zirc%C3%B4nio",
        niveldeenergia: "5",
        densidadeSTP: "6.52 g/cm³",
        densidadeliquido: "5.04 g/cm³",
        abundanciaUniverso: "0.00014%",
        grupo: "4",
        periodo: "5",
        bloco: "d",
        cor: "#D3D3D3",
        origemNome: "Do árabe 'zarqun', que significa 'coração vermelho' (da cor da pedra)",
        densidade: "6.52 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "41",
        nome: "Nióbio",
        tipo: "Metal de transição",
        simbolo: "Nb",
        massa: "92.906",
        configuracao: "[Kr] 4d4 5s1",
        estado: "Sólido",
        descobridor: "Charles Hatchett",
        descoberta: "1801",
        usos: "Aços especiais, supercondutores",
        wikipedia: "https://pt.wikipedia.org/wiki/N%C3%ADobio",
        niveldeenergia: "5",
        densidadeSTP: "8.57 g/cm³",
        densidadeliquido: "6.48 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "5",
        periodo: "5",
        bloco: "d",
        cor: "#8A8A8A",
        origemNome: "De Niobe, filha do rei de Lídia na mitologia grega",
        densidade: "8.57 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "42",
        nome: "Molibdênio",
        tipo: "Metal de transição",
        simbolo: "Mo",
        massa: "95.95",
        configuracao: "[Kr] 4d5 5s1",
        estado: "Sólido",
        descobridor: "Carl Wilhelm Scheele",
        descoberta: "1778",
        usos: "Aços, lâminas de facas",
        wikipedia: "https://pt.wikipedia.org/wiki/Molibd%C3%AAnio",
        niveldeenergia: "5",
        densidadeSTP: "10.22 g/cm³",
        densidadeliquido: "4.18 g/cm³",
        abundanciaUniverso: "0.00004%",
        grupo: "6",
        periodo: "5",
        bloco: "d",
        cor: "#9E9E9E",
        origemNome: "Do grego 'molybdos', que significa chumbo",
        densidade: "10.22 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "43",
        nome: "Tecnécio",
        tipo: "Metal de transição",
        simbolo: "Tc",
        massa: "98",
        configuracao: "[Kr] 4d5 5s2",
        estado: "Sólido",
        descobridor: "Seaborg, Arthur, et al.",
        descoberta: "1937",
        usos: "Radioterapia, medicina",
        wikipedia: "https://pt.wikipedia.org/wiki/Tecn%C3%A9cio",
        niveldeenergia: "5",
        densidadeSTP: "11.5 g/cm³",
        densidadeliquido: "7.0 g/cm³",
        abundanciaUniverso: "0%",
        grupo: "7",
        periodo: "5",
        bloco: "d",
        cor: "#4C4C4C",
        origemNome: "Do grego 'techne', que significa 'arte'",
        densidade: "11.5 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "44",
        nome: "Rutênio",
        tipo: "Metal de transição",
        simbolo: "Ru",
        massa: "101.07",
        configuracao: "[Kr] 4d7 5s1",
        estado: "Sólido",
        descobridor: "Karl Ernst Claus",
        descoberta: "1844",
        usos: "Ligas metálicas, catalisadores",
        wikipedia: "https://pt.wikipedia.org/wiki/Rut%C3%BAnio",
        niveldeenergia: "5",
        densidadeSTP: "12.37 g/cm³",
        densidadeliquido: "8.6 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "8",
        periodo: "5",
        bloco: "d",
        cor: "#787878",
        origemNome: "Do latim 'Ruthenia', que significa Rússia",
        densidade: "12.37 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "45",
        nome: "Ródio",
        tipo: "Metal de transição",
        simbolo: "Rh",
        massa: "102.91",
        configuracao: "[Kr] 4d8 5s1",
        estado: "Sólido",
        descobridor: "William Hyde Wollaston",
        descoberta: "1803",
        usos: "Catalisadores, joias",
        wikipedia: "https://pt.wikipedia.org/wiki/R%C3%B3dio",
        niveldeenergia: "5",
        densidadeSTP: "12.41 g/cm³",
        densidadeliquido: "8.3 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "9",
        periodo: "5",
        bloco: "d",
        cor: "#D3D3D3",
        origemNome: "Do grego 'rhodon', que significa rosa",
        densidade: "12.41 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "46",
        nome: "Paládio",
        tipo: "Metal de transição",
        simbolo: "Pd",
        massa: "106.42",
        configuracao: "[Kr] 4d10",
        estado: "Sólido",
        descobridor: "William Hyde Wollaston",
        descoberta: "1803",
        usos: "Catalisadores, joias",
        wikipedia: "https://pt.wikipedia.org/wiki/Pal%C3%A1dio",
        niveldeenergia: "5",
        densidadeSTP: "12.02 g/cm³",
        densidadeliquido: "9.0 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "10",
        periodo: "5",
        bloco: "d",
        cor: "#C0C0C0",
        origemNome: "Do nome da cidade de Palas, na Grécia",
        densidade: "12.02 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "47",
        nome: "Prata",
        tipo: "Metal de transição",
        simbolo: "Ag",
        massa: "107.868",
        configuracao: "[Kr] 4d10 5s1",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Joias, utensílios, eletrônicos",
        wikipedia: "https://pt.wikipedia.org/wiki/Prata",
        niveldeenergia: "5",
        densidadeSTP: "10.49 g/cm³",
        densidadeliquido: "9.1 g/cm³",
        abundanciaUniverso: "0.00001%",
        grupo: "11",
        periodo: "5",
        bloco: "d",
        cor: "#C0C0C0",
        origemNome: "Do latim 'argentum', que significa prata",
        densidade: "10.49 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "48",
        nome: "Cádmio",
        tipo: "Metal de transição",
        simbolo: "Cd",
        massa: "112.41",
        configuracao: "[Kr] 4d10 5s2",
        estado: "Sólido",
        descobridor: "Frederich Strohmeyer",
        descoberta: "1817",
        usos: "Baterias, galvanização",
        wikipedia: "https://pt.wikipedia.org/wiki/C%C3%A1dmio",
        niveldeenergia: "5",
        densidadeSTP: "8.65 g/cm³",
        densidadeliquido: "6.4 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "12",
        periodo: "5",
        bloco: "d",
        cor: "#E0E0E0",
        origemNome: "Do grego 'kadmeia', nome de um mineral",
        densidade: "8.65 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "49",
        nome: "Índio",
        tipo: "Metal pobre",
        simbolo: "In",
        massa: "114.82",
        configuracao: "[Kr] 4d10 5s2",
        estado: "Sólido",
        descobridor: "Ferdinand Reich e Theodor Richter",
        descoberta: "1863",
        usos: "Eletrônicos, semicondutores",
        wikipedia: "https://pt.wikipedia.org/wiki/%C3%8Dndio",
        niveldeenergia: "5",
        densidadeSTP: "7.31 g/cm³",
        densidadeliquido: "5.3 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "13",
        periodo: "5",
        bloco: "p",
        cor: "#D0D0E0",
        origemNome: "Do grego 'indos', que significa índigo",
        densidade: "7.31 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "50",
        nome: "Estanho",
        tipo: "Metal pobre",
        simbolo: "Sn",
        massa: "118.71",
        configuracao: "[Kr] 4d10 5s2 5p2",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Latas, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Estanho",
        niveldeenergia: "5",
        densidadeSTP: "7.31 g/cm³",
        densidadeliquido: "6.7 g/cm³",
        abundanciaUniverso: "0.00003%",
        grupo: "14",
        periodo: "5",
        bloco: "p",
        cor: "#C0C0C0",
        origemNome: "Do latim 'stannum', que significa estanho",
        densidade: "7.31 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "51",
        nome: "Antimônio",
        tipo: "Semi-metal",
        simbolo: "Sb",
        massa: "121.76",
        configuracao: "[Kr] 4d10 5s2 5p3",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Semicondutores, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Antim%C3%B4nio",
        niveldeenergia: "5",
        densidadeSTP: "6.68 g/cm³",
        densidadeliquido: "4.0 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "15",
        periodo: "5",
        bloco: "p",
        cor: "#B3B3CC",
        origemNome: "Do grego 'antimoni', que significa 'não é amigo do homem'",
        densidade: "6.68 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "52",
        nome: "Telúrio",
        tipo: "Semi-metal",
        simbolo: "Te",
        massa: "127.60",
        configuracao: "[Kr] 4d10 5s2 5p4",
        estado: "Sólido",
        descobridor: "Franz Joseph Müller",
        descoberta: "1782",
        usos: "Semicondutores, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Tel%C3%BArio",
        niveldeenergia: "5",
        densidadeSTP: "6.24 g/cm³",
        densidadeliquido: "5.0 g/cm³",
        abundanciaUniverso: "0.00001%",
        grupo: "16",
        periodo: "5",
        bloco: "p",
        cor: "#F0F0F0",
        origemNome: "Do latim 'telurium', que significa 'terra'",
        densidade: "6.24 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "53",
        nome: "Iodo",
        tipo: "Halogêneo",
        simbolo: "I",
        massa: "126.90",
        configuracao: "[Kr] 4d10 5s2 5p5",
        estado: "Sólido",
        descobridor: "Bernhard C. J. Balard",
        descoberta: "1811",
        usos: "Antisséptico, radioterapia",
        wikipedia: "https://pt.wikipedia.org/wiki/Iodo",
        niveldeenergia: "5",
        densidadeSTP: "4.93 g/cm³",
        densidadeliquido: "3.17 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "17",
        periodo: "5",
        bloco: "p",
        cor: "#8A2BE2",
        origemNome: "Do grego 'iodes', que significa 'violeta' (cor do vapor)",
        densidade: "4.93 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "54",
        nome: "Xenônio",
        tipo: "Gás nobre",
        simbolo: "Xe",
        massa: "131.29",
        configuracao: "[Kr] 4d10 5s2 5p6",
        estado: "Gasoso",
        descobridor: "William Ramsay e Morris Travers",
        descoberta: "1898",
        usos: "Iluminação, anestesia",
        wikipedia: "https://pt.wikipedia.org/wiki/Xen%C3%B4nio",
        niveldeenergia: "5",
        densidadeSTP: "5.894 g/L",
        densidadeliquido: "3.15 g/cm³",
        abundanciaUniverso: "0.000009%",
        grupo: "18",
        periodo: "5",
        bloco: "p",
        cor: "#8A8A8A",
        origemNome: "Do grego 'xenos', que significa 'estranho'",
        densidade: "5.894 g/L",
        radioatividade: "Não"
      },
      {
        numero: "55",
        nome: "Césio",
        tipo: "Metal alcalino",
        simbolo: "Cs",
        massa: "132.91",
        configuracao: "[Xe] 6s1",
        estado: "Sólido",
        descobridor: "Robert Bunsen e Gustav Kirchhoff",
        descoberta: "1860",
        usos: "Células fotovoltaicas, relógios atômicos",
        wikipedia: "https://pt.wikipedia.org/wiki/C%C3%A9sio",
        niveldeenergia: "6",
        densidadeSTP: "1.93 g/cm³",
        densidadeliquido: "1.21 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "1",
        periodo: "6",
        bloco: "s",
        cor: "#B5B5E5",
        origemNome: "Do latim 'caesius', que significa 'azul-céu'",
        densidade: "1.93 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "56",
        nome: "Bário",
        tipo: "Metal alcalino-terroso",
        simbolo: "Ba",
        massa: "137.33",
        configuracao: "[Xe] 6s2",
        estado: "Sólido",
        descobridor: "Carl Wilhelm Scheele",
        descoberta: "1772",
        usos: "Luminárias, fogos de artifício",
        wikipedia: "https://pt.wikipedia.org/wiki/B%C3%A1rio",
        niveldeenergia: "6",
        densidadeSTP: "3.62 g/cm³",
        densidadeliquido: "2.2 g/cm³",
        abundanciaUniverso: "0.00005%",
        grupo: "2",
        periodo: "6",
        bloco: "s",
        cor: "#90EE90",
        origemNome: "Do grego 'barys', que significa 'pesado'",
        densidade: "3.62 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "72",
        nome: "Háfnio",
        tipo: "Metal de transição",
        simbolo: "Hf",
        massa: "178.49",
        configuracao: "[Xe] 4f14 5d2 6s2",
        estado: "Sólido",
        descobridor: "Dmitri Mendeleev",
        descoberta: "1923",
        usos: "Ligação de ligas, reatores nucleares",
        wikipedia: "https://pt.wikipedia.org/wiki/H%C3%A1fnio",
        niveldeenergia: "6",
        densidadeSTP: "13.31 g/cm³",
        densidadeliquido: "9.65 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "4",
        periodo: "6",
        bloco: "d",
        cor: "#1C1C1C",
        origemNome: "Do nome da cidade de Copenhague, Dinamarca (Hafnia)",
        densidade: "13.31 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "73",
        nome: "Tântalo",
        tipo: "Metal de transição",
        simbolo: "Ta",
        massa: "180.95",
        configuracao: "[Xe] 4f14 5d3 6s2",
        estado: "Sólido",
        descobridor: "Anders Ekeberg",
        descoberta: "1802",
        usos: "Capacitores, implantes médicos",
        wikipedia: "https://pt.wikipedia.org/wiki/T%C3%A2ntalo",
        niveldeenergia: "6",
        densidadeSTP: "16.69 g/cm³",
        densidadeliquido: "14.7 g/cm³",
        abundanciaUniverso: "0.00002%",
        grupo: "5",
        periodo: "6",
        bloco: "d",
        cor: "#0000B3",
        origemNome: "Do grego 'Tantalos', nome do rei da mitologia grega",
        densidade: "16.69 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "74",
        nome: "Wolframio",
        tipo: "Metal de transição",
        simbolo: "W",
        massa: "183.84",
        configuracao: "[Xe] 4f14 5d4 6s2",
        estado: "Sólido",
        descobridor: "Carl Wilhelm Scheele e Torbern O. Bergman",
        descoberta: "1783",
        usos: "Filamentos de lâmpadas, aço",
        wikipedia: "https://pt.wikipedia.org/wiki/Wolframio",
        niveldeenergia: "6",
        densidadeSTP: "19.25 g/cm³",
        densidadeliquido: "17.0 g/cm³",
        abundanciaUniverso: "0.00001%",
        grupo: "6",
        periodo: "6",
        bloco: "d",
        cor: "#B3B3B3",
        origemNome: "Do alemão 'wolf rahm', que significa 'lama do lobo'",
        densidade: "19.25 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "75",
        nome: "Rênio",
        tipo: "Metal de transição",
        simbolo: "Re",
        massa: "186.21",
        configuracao: "[Xe] 4f14 5d5 6s2",
        estado: "Sólido",
        descobridor: "Masataka Ogawa",
        descoberta: "1925",
        usos: "Ligas de alta temperatura, catalisadores",
        wikipedia: "https://pt.wikipedia.org/wiki/R%C3%AAnio",
        niveldeenergia: "6",
        densidadeSTP: "21.02 g/cm³",
        densidadeliquido: "19.0 g/cm³",
        abundanciaUniverso: "0.000001%",
        grupo: "7",
        periodo: "6",
        bloco: "d",
        cor: "#D3D3D3",
        origemNome: "Do latim 'rhenus', que significa 'Reno'",
        densidade: "21.02 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "76",
        nome: "Osmio",
        tipo: "Metal de transição",
        simbolo: "Os",
        massa: "190.23",
        configuracao: "[Xe] 4f14 5d6 6s2",
        estado: "Sólido",
        descobridor: "Smithson Tennant",
        descoberta: "1803",
        usos: "Ligas de alta dureza, contato elétrico",
        wikipedia: "https://pt.wikipedia.org/wiki/Osmio",
        niveldeenergia: "6",
        densidadeSTP: "22.59 g/cm³",
        densidadeliquido: "22.59 g/cm³",
        abundanciaUniverso: "0.000001%",
        grupo: "8",
        periodo: "6",
        bloco: "d",
        cor: "#9E9E9E",
        origemNome: "Do grego 'osme', que significa 'odor'",
        densidade: "22.59 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "77",
        nome: "Irídio",
        tipo: "Metal de transição",
        simbolo: "Ir",
        massa: "192.22",
        configuracao: "[Xe] 4f14 5d7 6s2",
        estado: "Sólido",
        descobridor: "Smithson Tennant",
        descoberta: "1803",
        usos: "Ligas de alta resistência, contatos elétricos",
        wikipedia: "https://pt.wikipedia.org/wiki/Ir%C3%ADdio",
        niveldeenergia: "6",
        densidadeSTP: "22.56 g/cm³",
        densidadeliquido: "22.56 g/cm³",
        abundanciaUniverso: "0.000001%",
        grupo: "9",
        periodo: "6",
        bloco: "d",
        cor: "#A0A0A0",
        origemNome: "Do grego 'iris', que significa 'arco-íris'",
        densidade: "22.56 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "78",
        nome: "Platina",
        tipo: "Metal de transição",
        simbolo: "Pt",
        massa: "195.08",
        configuracao: "[Xe] 4f14 5d9 6s1",
        estado: "Sólido",
        descobridor: "Antonio de Ulloa",
        descoberta: "1735",
        usos: "Catalisadores, joias",
        wikipedia: "https://pt.wikipedia.org/wiki/Platina",
        niveldeenergia: "6",
        densidadeSTP: "21.45 g/cm³",
        densidadeliquido: "19.8 g/cm³",
        abundanciaUniverso: "0.000003%",
        grupo: "10",
        periodo: "6",
        bloco: "d",
        cor: "#C0C0C0",
        origemNome: "Do espanhol 'platina', que significa 'ouro pequeno'",
        densidade: "21.45 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "79",
        nome: "Ouro",
        tipo: "Metal de transição",
        simbolo: "Au",
        massa: "196.97",
        configuracao: "[Xe] 4f14 5d10 6s1",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Joias, eletrônicos",
        wikipedia: "https://pt.wikipedia.org/wiki/Ouro",
        niveldeenergia: "6",
        densidadeSTP: "19.32 g/cm³",
        densidadeliquido: "17.31 g/cm³",
        abundanciaUniverso: "0.000004%",
        grupo: "11",
        periodo: "6",
        bloco: "d",
        cor: "#FFD700",
        origemNome: "Do latim 'aurum', que significa 'brilhante'",
        densidade: "19.32 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "80",
        nome: "Mercúrio",
        tipo: "Metal de transição",
        simbolo: "Hg",
        massa: "200.59",
        configuracao: "[Xe] 4f14 5d10 6s2",
        estado: "Líquido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Termômetros, lâmpadas",
        wikipedia: "https://pt.wikipedia.org/wiki/Merc%C3%BArio",
        niveldeenergia: "6",
        densidadeSTP: "13.55 g/cm³",
        densidadeliquido: "13.55 g/cm³",
        abundanciaUniverso: "0.000003%",
        grupo: "12",
        periodo: "6",
        bloco: "d",
        cor: "#B0B0B0",
        origemNome: "Do latim 'hydrargyrum', que significa 'prata líquida'",
        densidade: "13.55 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "81",
        nome: "Tálio",
        tipo: "Metal pesado",
        simbolo: "Tl",
        massa: "204.38",
        configuracao: "[Xe] 4f14 5d10 6s2 6p1",
        estado: "Sólido",
        descobridor: "William Crookes",
        descoberta: "1861",
        usos: "Lâmpadas, componentes eletrônicos",
        wikipedia: "https://pt.wikipedia.org/wiki/T%C3%A1lio",
        niveldeenergia: "6",
        densidadeSTP: "11.85 g/cm³",
        densidadeliquido: "9.32 g/cm³",
        abundanciaUniverso: "0.000003%",
        grupo: "13",
        periodo: "6",
        bloco: "p",
        cor: "#D0D0D0",
        origemNome: "Do grego 'thallos', que significa 'broto verde'",
        densidade: "11.85 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "82",
        nome: "Chumbo",
        tipo: "Metal pesado",
        simbolo: "Pb",
        massa: "207.2",
        configuracao: "[Xe] 4f14 5d10 6s2 6p2",
        estado: "Sólido",
        descobridor: "Antiguidade",
        descoberta: "Antiguidade",
        usos: "Baterias, proteção contra radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Chumbo",
        niveldeenergia: "6",
        densidadeSTP: "11.34 g/cm³",
        densidadeliquido: "10.66 g/cm³",
        abundanciaUniverso: "0.000004%",
        grupo: "14",
        periodo: "6",
        bloco: "p",
        cor: "#808080",
        origemNome: "Do latim 'plumbum', que significa 'chumbo'",
        densidade: "11.34 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "83",
        nome: "Bismuto",
        tipo: "Metal pesado",
        simbolo: "Bi",
        massa: "208.98",
        configuracao: "[Xe] 4f14 5d10 6s2 6p3",
        estado: "Sólido",
        descobridor: "Claude François Geoffroy",
        descoberta: "1753",
        usos: "Cosméticos, ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Bismuto",
        niveldeenergia: "6",
        densidadeSTP: "9.78 g/cm³",
        densidadeliquido: "7.3 g/cm³",
        abundanciaUniverso: "0.000004%",
        grupo: "15",
        periodo: "6",
        bloco: "p",
        cor: "#F0F0F0",
        origemNome: "Do alemão 'wismut', que significa 'lixo'",
        densidade: "9.78 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "84",
        nome: "Polônio",
        tipo: "Semi-metal",
        simbolo: "Po",
        massa: "209.98",
        configuracao: "[Xe] 4f14 5d10 6s2 6p4",
        estado: "Sólido",
        descobridor: "Marie Curie e Pierre Curie",
        descoberta: "1898",
        usos: "Fontes de radiação, anticâncer",
        wikipedia: "https://pt.wikipedia.org/wiki/Pol%C3%B4nio",
        niveldeenergia: "6",
        densidadeSTP: "9.32 g/cm³",
        densidadeliquido: "7.5 g/cm³",
        abundanciaUniverso: "0.000001%",
        grupo: "16",
        periodo: "6",
        bloco: "p",
        cor: "#B0B0B0",
        origemNome: "Do país Polônia, em homenagem ao país natal dos descobridores",
        densidade: "9.32 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "85",
        nome: "Astatino",
        tipo: "Halogêneo",
        simbolo: "At",
        massa: "210",
        configuracao: "[Xe] 4f14 5d10 6s2 6p5",
        estado: "Sólido",
        descobridor: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
        descoberta: "1940",
        usos: "Radiação terapêutica, pesquisa nuclear",
        wikipedia: "https://pt.wikipedia.org/wiki/Astatino",
        niveldeenergia: "6",
        densidadeSTP: "6.4 g/cm³",
        densidadeliquido: "5.0 g/cm³",
        abundanciaUniverso: "0.00000004%",
        grupo: "17",
        periodo: "6",
        bloco: "p",
        cor: "#D1C9A3",
        origemNome: "Do grego 'astatos', que significa 'instável'",
        densidade: "6.4 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "86",
        nome: "Radônio",
        tipo: "Gás nobre",
        simbolo: "Rn",
        massa: "222",
        configuracao: "[Xe] 4f14 5d10 6s2 6p6",
        estado: "Gasoso",
        descobridor: "Frederick Dorn",
        descoberta: "1899",
        usos: "Tratamento de câncer, radioterapia",
        wikipedia: "https://pt.wikipedia.org/wiki/Rad%C3%B4nio",
        niveldeenergia: "6",
        densidadeSTP: "9.73 g/L",
        densidadeliquido: "4.4 g/cm³",
        abundanciaUniverso: "0.00000003%",
        grupo: "18",
        periodo: "6",
        bloco: "p",
        cor: "#E8E8E8",
        origemNome: "Do latim 'radon', de radiação",
        densidade: "9.73 g/L",
        radioatividade: "Sim"
      },
      {
        numero: "87",
        nome: "Frâncio",
        tipo: "Metal alcalino-terroso",
        simbolo: "Fr",
        massa: "223",
        configuracao: "[Rn] 7s1",
        estado: "Sólido",
        descobridor: "Marguerite Perey",
        descoberta: "1939",
        usos: "Pesquisa científica, fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Fr%C3%A2ncio",
        niveldeenergia: "7",
        densidadeSTP: "1.87 g/cm³",
        densidadeliquido: "1.50 g/cm³",
        abundanciaUniverso: "0.000000001%",
        grupo: "1",
        periodo: "7",
        bloco: "s",
        cor: "#E7A1A1",
        origemNome: "Do nome da França",
        densidade: "1.87 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "88",
        nome: "Radônio",
        tipo: "Metal de transição",
        simbolo: "Ra",
        massa: "226",
        configuracao: "[Rn] 7s2",
        estado: "Sólido",
        descobridor: "Marie Curie, Pierre Curie e André Debierne",
        descoberta: "1898",
        usos: "Tratamento de câncer, fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/R%C3%A1dio",
        niveldeenergia: "7",
        densidadeSTP: "5.5 g/cm³",
        densidadeliquido: "4.8 g/cm³",
        abundanciaUniverso: "0.00000003%",
        grupo: "2",
        periodo: "7",
        bloco: "s",
        cor: "#FFFFFF",
        origemNome: "Do latim 'radius', que significa 'raio'",
        densidade: "5.5 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "104",
        nome: "Rutherfórdio",
        tipo: "Metal de transição",
        simbolo: "Rf",
        massa: "267",
        configuracao: "[Rn] 5f14 6d2 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Torbjørn Sikkeland",
        descoberta: "1964",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Rutherf%C3%B3rdio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "4",
        periodo: "7",
        bloco: "d",
        cor: "#8A8A8A",
        origemNome: "Em homenagem ao físico Ernest Rutherford",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "105",
        nome: "Dúbnio",
        tipo: "Metal de transição",
        simbolo: "Db",
        massa: "270",
        configuracao: "[Rn] 5f14 6d3 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1970",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/D%C3%BAbnio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "5",
        periodo: "7",
        bloco: "d",
        cor: "#A1A1A1",
        origemNome: "Em homenagem à cidade de Dubna, na Rússia",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "106",
        nome: "Seabórgio",
        tipo: "Metal de transição",
        simbolo: "Sg",
        massa: "271",
        configuracao: "[Rn] 5f14 6d4 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1974",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Seab%C3%B3rgio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "6",
        periodo: "7",
        bloco: "d",
        cor: "#B1B1B1",
        origemNome: "Em homenagem ao físico Glenn T. Seaborg",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "107",
        nome: "Bohrium",
        tipo: "Metal de transição",
        simbolo: "Bh",
        massa: "270",
        configuracao: "[Rn] 5f14 6d5 7s2",
        estado: "Sólido",
        descobridor: "Hermann Brenner, Peter Armbruster, Gertrud A. de Wanger",
        descoberta: "1981",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/B%C3%B3hrio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "7",
        periodo: "7",
        bloco: "d",
        cor: "#C1C1C1",
        origemNome: "Em homenagem ao físico Niels Bohr",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "108",
        nome: "Hássio",
        tipo: "Metal de transição",
        simbolo: "Hs",
        massa: "277",
        configuracao: "[Rn] 5f14 6d6 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1984",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/H%C3%A1ssio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "8",
        periodo: "7",
        bloco: "d",
        cor: "#D1D1D1",
        origemNome: "Em homenagem à cidade de Darmstadt, na Alemanha",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "109",
        nome: "Meitnério",
        tipo: "Metal de transição",
        simbolo: "Mt",
        massa: "278",
        configuracao: "[Rn] 5f14 6d7 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1982",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Meitn%C3%A9rio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "9",
        periodo: "7",
        bloco: "d",
        cor: "#E1E1E1",
        origemNome: "Em homenagem ao físico Kurt Meitner",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "110",
        nome: "Darmstádio",
        tipo: "Metal de transição",
        simbolo: "Ds",
        massa: "281",
        configuracao: "[Rn] 5f14 6d8 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1994",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Darmst%C3%A1dio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "10",
        periodo: "7",
        bloco: "d",
        cor: "#F1F1F1",
        origemNome: "Em homenagem à cidade de Darmstadt, na Alemanha",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "111",
        nome: "Röntgênio",
        tipo: "Metal de transição",
        simbolo: "Rg",
        massa: "280",
        configuracao: "[Rn] 5f14 6d9 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1994",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/R%C3%B6ntg%C3%AAnio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "11",
        periodo: "7",
        bloco: "d",
        cor: "#F2F2F2",
        origemNome: "Em homenagem ao físico Wilhelm Röntgen",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "112",
        nome: "Copernício",
        tipo: "Metal de transição",
        simbolo: "Cn",
        massa: "285",
        configuracao: "[Rn] 5f14 6d10 7s2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "2009",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Copern%C3%ADcio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "12",
        periodo: "7",
        bloco: "d",
        cor: "#D8D8D8",
        origemNome: "Em homenagem ao astrônomo Nicolau Copérnico",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "113",
        nome: "Nihônio",
        tipo: "Metal de transição",
        simbolo: "Nh",
        massa: "284",
        configuracao: "[Rn] 5f14 6d10 7s2",
        estado: "Sólido",
        descobridor: "RIKEN",
        descoberta: "2004",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Nih%C3%B4nio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "13",
        periodo: "7",
        bloco: "p",
        cor: "#B9B9B9",
        origemNome: "Em homenagem ao Japão (nihon)",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "114",
        nome: "Fleróvio",
        tipo: "Metal pesado",
        simbolo: "Fl",
        massa: "289",
        configuracao: "[Rn] 5f14 6d10 7s2 7p2",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "1999",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Fler%C3%B3vio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "14",
        periodo: "7",
        bloco: "p",
        cor: "#C7C7C7",
        origemNome: "Em homenagem à cidade de Flerov",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "115",
        nome: "Moscóvio",
        tipo: "Metal pesado",
        simbolo: "Mc",
        massa: "288",
        configuracao: "[Rn] 5f14 6d10 7s2 7p3",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "2004",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Mosc%C3%B3vio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "15",
        periodo: "7",
        bloco: "p",
        cor: "#9A9A9A",
        origemNome: "Em homenagem à cidade de Moscovo",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "116",
        nome: "Livermório",
        tipo: "Metal pesado",
        simbolo: "Lv",
        massa: "293",
        configuracao: "[Rn] 5f14 6d10 7s2 7p4",
        estado: "Sólido",
        descobridor: "Lawrence Livermore National Laboratory",
        descoberta: "2000",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Liverm%C3%B3rio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "16",
        periodo: "7",
        bloco: "p",
        cor: "#A8A8A8",
        origemNome: "Em homenagem ao laboratório Lawrence Livermore",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "117",
        nome: "Tennessino",
        tipo: "Metal pesado",
        simbolo: "Ts",
        massa: "294",
        configuracao: "[Rn] 5f14 6d10 7s2 7p5",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "2010",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Tenness%C3%ADnio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "17",
        periodo: "7",
        bloco: "p",
        cor: "#B9B9B9",
        origemNome: "Em homenagem ao estado do Tennessee",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "118",
        nome: "Oganessônio",
        tipo: "Gás nobre",
        simbolo: "Og",
        massa: "294",
        configuracao: "[Rn] 5f14 6d10 7s2 7p6",
        estado: "Sólido",
        descobridor: "Joint Institute for Nuclear Research (JINR)",
        descoberta: "2002",
        usos: "Pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Oganess%C3%B3nio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "N/A",
        grupo: "18",
        periodo: "7",
        bloco: "p",
        cor: "#C7C7C7",
        origemNome: "Em homenagem ao físico Yuri Oganessian",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "57",
        nome: "Lantânio",
        tipo: "Lantanídeo",
        simbolo: "La",
        massa: "138.90547",
        configuracao: "[Xe] 4f1 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1839",
        usos: "Produção de ligas, fabricação de dispositivos ópticos e catalisadores",
        wikipedia: "https://pt.wikipedia.org/wiki/Lant%C3%A2nio",
        niveldeenergia: "6",
        densidadeSTP: "6.162 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00016%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#B5B5B5",
        origemNome: "Do grego 'lanthanein' (esconder-se), devido à sua descoberta tardia",
        densidade: "6.162 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "58",
        nome: "Cério",
        tipo: "Lantanídeo",
        simbolo: "Ce",
        massa: "140.116",
        configuracao: "[Xe] 4f2 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1803",
        usos: "Catalisadores, baterias, vidro, ligas de metais",
        wikipedia: "https://pt.wikipedia.org/wiki/C%C3%A9rio",
        niveldeenergia: "6",
        densidadeSTP: "6.770 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00025%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#D6D6D6",
        origemNome: "Em homenagem ao asteroide Ceres",
        densidade: "6.770 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "59",
        nome: "Praseodímio",
        tipo: "Lantanídeo",
        simbolo: "Pr",
        massa: "140.907",
        configuracao: "[Xe] 4f3 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1885",
        usos: "Ligas, magnetos, e produção de corantes",
        wikipedia: "https://pt.wikipedia.org/wiki/Praseod%C3%ADmio",
        niveldeenergia: "6",
        densidadeSTP: "6.77 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00019%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#A8A8A8",
        origemNome: "Do grego 'prasios' (verde), devido à cor da sua solução",
        densidade: "6.77 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "60",
        nome: "Neodímio",
        tipo: "Lantanídeo",
        simbolo: "Nd",
        massa: "144.242",
        configuracao: "[Xe] 4f4 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1841",
        usos: "Ímãs permanentes, lasers, e em várias ligas metálicas",
        wikipedia: "https://pt.wikipedia.org/wiki/Neod%C3%ADmio",
        niveldeenergia: "6",
        densidadeSTP: "7.005 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00012%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#98A4A4",
        origemNome: "Do grego 'neos' (novo) e 'demos' (povo), pois foi isolado de outros elementos",
        densidade: "7.005 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "61",
        nome: "Promécio",
        tipo: "Lantanídeo",
        simbolo: "Pm",
        massa: "145",
        configuracao: "[Xe] 4f5 5d1 6s2",
        estado: "Sólido",
        descobridor: "Marvin E. Baringer, Jacob A. Marinsky, Lawrence E. Glendenin",
        descoberta: "1945",
        usos: "Fontes de radiação, fontes de energia para satélites",
        wikipedia: "https://pt.wikipedia.org/wiki/Prom%C3%A9cio",
        niveldeenergia: "6",
        densidadeSTP: "7.26 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#B1B1B1",
        origemNome: "Em homenagem ao titã grego Prometeu",
        densidade: "7.26 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "62",
        nome: "Samário",
        tipo: "Lantanídeo",
        simbolo: "Sm",
        massa: "150.36",
        configuracao: "[Xe] 4f6 5d1 6s2",
        estado: "Sólido",
        descobridor: "Paul-Émile Lecoq de Boisbaudran",
        descoberta: "1879",
        usos: "Imãs, catalisadores, e como material de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Sam%C3%A1rio",
        niveldeenergia: "6",
        densidadeSTP: "7.52 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.0001%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#9C9C9C",
        origemNome: "Em homenagem à cidade de Samara, na Rússia",
        densidade: "7.52 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "63",
        nome: "Európio",
        tipo: "Lantanídeo",
        simbolo: "Eu",
        massa: "151.98",
        configuracao: "[Xe] 4f7 5d1 6s2",
        estado: "Sólido",
        descobridor: "Jean Charles Galissard de Marignac",
        descoberta: "1890",
        usos: "Fósforos, lasers, e componentes de aparelhos eletrônicos",
        wikipedia: "https://pt.wikipedia.org/wiki/Eu%C3%ADpio",
        niveldeenergia: "6",
        densidadeSTP: "5.243 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.000025%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#D2D2D2",
        origemNome: "Em homenagem à região de Évora, em Portugal",
        densidade: "5.243 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "64",
        nome: "Gadolínio",
        tipo: "Lantanídeo",
        simbolo: "Gd",
        massa: "157.25",
        configuracao: "[Xe] 4f7 5d1 6s2",
        estado: "Sólido",
        descobridor: "Johan Gadolin",
        descoberta: "1880",
        usos: "Imãs, contrastes em exames de ressonância magnética, e ligas de alta resistência",
        wikipedia: "https://pt.wikipedia.org/wiki/Gadol%C3%ADnio",
        niveldeenergia: "6",
        densidadeSTP: "7.90 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.0005%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#C3C3C3",
        origemNome: "Em homenagem ao químico finlandês Johan Gadolin",
        densidade: "7.90 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "65",
        nome: "Terbium",
        tipo: "Lantanídeo",
        simbolo: "Tb",
        massa: "158.925",
        configuracao: "[Xe] 4f9 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1843",
        usos: "Imãs, telas de fósforo, e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/T%C3%A9rbio",
        niveldeenergia: "6",
        densidadeSTP: "8.230 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00012%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#8B8B8B",
        origemNome: "Em homenagem ao mineral terbium",
        densidade: "8.230 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "66",
        nome: "Disprósio",
        tipo: "Lantanídeo",
        simbolo: "Dy",
        massa: "162.50",
        configuracao: "[Xe] 4f10 5d1 6s2",
        estado: "Sólido",
        descobridor: "Paul-Émile Lecoq de Boisbaudran",
        descoberta: "1886",
        usos: "Imãs permanentes e em reatores nucleares",
        wikipedia: "https://pt.wikipedia.org/wiki/Dispr%C3%B3sio",
        niveldeenergia: "6",
        densidadeSTP: "8.550 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00013%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#767676",
        origemNome: "Em homenagem à cidade de Dispros, na Grécia",
        densidade: "8.550 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "67",
        nome: "Hólmio",
        tipo: "Lantanídeo",
        simbolo: "Ho",
        massa: "164.93033",
        configuracao: "[Xe] 4f11 5d1 6s2",
        estado: "Sólido",
        descobridor: "Per Theodor Cleve",
        descoberta: "1878",
        usos: "Imãs, lasers, e amplificadores de fibra ótica",
        wikipedia: "https://pt.wikipedia.org/wiki/H%C3%B3lmio",
        niveldeenergia: "6",
        densidadeSTP: "8.795 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00018%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#9E9E9E",
        origemNome: "Em homenagem à cidade de Estocolmo (nome em latim, Holmiae)",
        densidade: "8.795 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "68",
        nome: "Érbio",
        tipo: "Lantanídeo",
        simbolo: "Er",
        massa: "167.259",
        configuracao: "[Xe] 4f12 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1843",
        usos: "Dispositivos óticos, laser, e imãs",
        wikipedia: "https://pt.wikipedia.org/wiki/%C3%89rbio",
        niveldeenergia: "6",
        densidadeSTP: "9.066 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00007%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#A6A6A6",
        origemNome: "Em homenagem à cidade de Ytterby, na Suécia",
        densidade: "9.066 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "69",
        nome: "Tulio",
        tipo: "Lantanídeo",
        simbolo: "Tm",
        massa: "168.93422",
        configuracao: "[Xe] 4f13 5d1 6s2",
        estado: "Sólido",
        descobridor: "Per Theodor Cleve",
        descoberta: "1879",
        usos: "Lasers e dispositivos óticos",
        wikipedia: "https://pt.wikipedia.org/wiki/T%C3%BAlio",
        niveldeenergia: "6",
        densidadeSTP: "9.32 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00004%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#B0B0B0",
        origemNome: "Em homenagem à cidade de Tullinge, na Suécia",
        densidade: "9.32 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "70",
        nome: "Ítérbio",
        tipo: "Lantanídeo",
        simbolo: "Yb",
        massa: "173.04",
        configuracao: "[Xe] 4f14 6s2",
        estado: "Sólido",
        descobridor: "Carl Gustaf Mosander",
        descoberta: "1843",
        usos: "Lasers e como fonte de radiação em pesquisas",
        wikipedia: "https://pt.wikipedia.org/wiki/%C3%8Dt%C3%A9rbio",
        niveldeenergia: "6",
        densidadeSTP: "6.57 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00003%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#A8A8A8",
        origemNome: "Em homenagem à cidade de Ytterby, na Suécia",
        densidade: "6.57 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "71",
        nome: "Lutécio",
        tipo: "Lantanídeo",
        simbolo: "Lu",
        massa: "174.9668",
        configuracao: "[Xe] 4f14 5d1 6s2",
        estado: "Sólido",
        descobridor: "Carl Auer von Welsbach",
        descoberta: "1907",
        usos: "Catalisadores e lasers",
        wikipedia: "https://pt.wikipedia.org/wiki/Lut%C3%A9cio",
        niveldeenergia: "6",
        densidadeSTP: "9.84 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00002%",
        grupo: "3",
        periodo: "6",
        bloco: "f",
        cor: "#9C9C9C",
        origemNome: "Em homenagem à cidade de Paris (Lutetia)",
        densidade: "9.84 g/cm³",
        radioatividade: "Não"
      },
      {
        numero: "89",
        nome: "Actínio",
        tipo: "Actinídeo",
        simbolo: "Ac",
        massa: "227",
        configuracao: "[Rn] 6d1 7s2",
        estado: "Sólido",
        descobridor: "Friedrich Oskar Giesel",
        descoberta: "1899",
        usos: "Fontes de radiação e em tratamentos médicos de câncer",
        wikipedia: "https://pt.wikipedia.org/wiki/Act%C3%ADnio",
        niveldeenergia: "7",
        densidadeSTP: "4.968 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00003%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#B9B9B9",
        origemNome: "Do grego 'aktis' (raio), devido à sua radioatividade",
        densidade: "4.968 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "90",
        nome: "Tório",
        tipo: "Actinídeo",
        simbolo: "Th",
        massa: "232.0377",
        configuracao: "[Rn] 6d2 7s2",
        estado: "Sólido",
        descobridor: "Jöns Jakob Berzelius",
        descoberta: "1828",
        usos: "Combustível nuclear, ligas de alta resistência, e em tratamentos médicos",
        wikipedia: "https://pt.wikipedia.org/wiki/T%C3%B3rio",
        niveldeenergia: "7",
        densidadeSTP: "11.72 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00003%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#A0A0A0",
        origemNome: "Em homenagem ao deus nórdico Thor",
        densidade: "11.72 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "91",
        nome: "Protactínio",
        tipo: "Actinídeo",
        simbolo: "Pa",
        massa: "231.03588",
        configuracao: "[Rn] 5f2 6d1 7s2",
        estado: "Sólido",
        descobridor: "Otto Hahn, Lise Meitner",
        descoberta: "1899",
        usos: "Fonte de radiação e em estudos nucleares",
        wikipedia: "https://pt.wikipedia.org/wiki/Protact%C3%ADnio",
        niveldeenergia: "7",
        densidadeSTP: "15.37 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00002%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#A8A8A8",
        origemNome: "Do grego 'protos' (anterior) e 'aktis' (raio), pois é precursor do urânio",
        densidade: "15.37 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "92",
        nome: "Urânio",
        tipo: "Actinídeo",
        simbolo: "U",
        massa: "238.02891",
        configuracao: "[Rn] 5f3 6d1 7s2",
        estado: "Sólido",
        descobridor: "Martin Heinrich Klaproth",
        descoberta: "1789",
        usos: "Combustível nuclear, ligas metálicas e tratamentos médicos",
        wikipedia: "https://pt.wikipedia.org/wiki/Ur%C3%A2nio",
        niveldeenergia: "7",
        densidadeSTP: "18.95 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0.00012%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#C3C3C3",
        origemNome: "Em homenagem ao planeta Urano",
        densidade: "18.95 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "93",
        nome: "Neptúnio",
        tipo: "Actinídeo",
        simbolo: "Np",
        massa: "237",
        configuracao: "[Rn] 5f4 6d1 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Arthur C. Wahl, Joseph W. Kennedy",
        descoberta: "1940",
        usos: "Produção de energia nuclear e em reatores",
        wikipedia: "https://pt.wikipedia.org/wiki/Nept%C3%BAnio",
        niveldeenergia: "7",
        densidadeSTP: "20.45 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#A1A1A1",
        origemNome: "Em homenagem ao planeta Netuno",
        densidade: "20.45 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "94",
        nome: "Plutônio",
        tipo: "Actinídeo",
        simbolo: "Pu",
        massa: "244",
        configuracao: "[Rn] 5f6 6d1 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Albert Ghiorso, Ralph A. James",
        descoberta: "1940",
        usos: "Combustível nuclear e para armas nucleares",
        wikipedia: "https://pt.wikipedia.org/wiki/Plut%C3%B4nio",
        niveldeenergia: "7",
        densidadeSTP: "19.86 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#A3A3A3",
        origemNome: "Em homenagem ao planeta Plutão",
        densidade: "19.86 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "95",
        nome: "Amerício",
        tipo: "Actinídeo",
        simbolo: "Am",
        massa: "243",
        configuracao: "[Rn] 5f7 6d1 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Albert Ghiorso, Ralph A. James",
        descoberta: "1944",
        usos: "Fontes de radiação, dispositivos de detecção de fumaça",
        wikipedia: "https://pt.wikipedia.org/wiki/Amer%C3%ADcio",
        niveldeenergia: "7",
        densidadeSTP: "13.67 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#B0B0B0",
        origemNome: "Em homenagem ao continente América",
        densidade: "13.67 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "96",
        nome: "Cúrio",
        tipo: "Actinídeo",
        simbolo: "Cm",
        massa: "247",
        configuracao: "[Rn] 5f7 6d2 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Albert Ghiorso, Ralph A. James",
        descoberta: "1944",
        usos: "Fontes de radiação e na pesquisa nuclear",
        wikipedia: "https://pt.wikipedia.org/wiki/C%C3%BArio",
        niveldeenergia: "7",
        densidadeSTP: "13.51 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#D0D0D0",
        origemNome: "Em homenagem a Marie e Pierre Curie",
        densidade: "13.51 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "97",
        nome: "Berquélio",
        tipo: "Actinídeo",
        simbolo: "Bk",
        massa: "247",
        configuracao: "[Rn] 5f9 6d2 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Albert Ghiorso, Ralph A. James",
        descoberta: "1949",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Berqu%C3%A9lio",
        niveldeenergia: "7",
        densidadeSTP: "14.78 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#C0C0C0",
        origemNome: "Em homenagem à cidade de Berkeley, Califórnia",
        densidade: "14.78 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "98",
        nome: "Califórnio",
        tipo: "Actinídeo",
        simbolo: "Cf",
        massa: "251",
        configuracao: "[Rn] 5f10 6d2 7s2",
        estado: "Sólido",
        descobridor: "Glenn T. Seaborg, Albert Ghiorso, Ralph A. James",
        descoberta: "1950",
        usos: "Fontes de radiação, tratamentos médicos e pesquisa científica",
        wikipedia: "https://pt.wikipedia.org/wiki/Calif%C3%B3rnio",
        niveldeenergia: "7",
        densidadeSTP: "15.10 g/cm³",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#B9B9B9",
        origemNome: "Em homenagem ao estado da Califórnia",
        densidade: "15.10 g/cm³",
        radioatividade: "Sim"
      },
      {
        numero: "99",
        nome: "Einsteínio",
        tipo: "Actinídeo",
        simbolo: "Es",
        massa: "252",
        configuracao: "[Rn] 5f11 6d1 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Ralph A. James",
        descoberta: "1952",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Einste%C3%ADnio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#D1D1D1",
        origemNome: "Em homenagem a Albert Einstein",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "100",
        nome: "Férmio",
        tipo: "Actinídeo",
        simbolo: "Fm",
        massa: "257",
        configuracao: "[Rn] 5f12 6d1 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Ralph A. James",
        descoberta: "1952",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/F%C3%A9rmio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#E0E0E0",
        origemNome: "Em homenagem a Enrico Fermi",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "101",
        nome: "Mendelévio",
        tipo: "Actinídeo",
        simbolo: "Md",
        massa: "258",
        configuracao: "[Rn] 5f13 6d1 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Ralph A. James",
        descoberta: "1955",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Mendel%C3%A9vio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#E8E8E8",
        origemNome: "Em homenagem a Dmitri Mendeléyev, criador da tabela periódica",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "102",
        nome: "Nobelium",
        tipo: "Actinídeo",
        simbolo: "No",
        massa: "259",
        configuracao: "[Rn] 5f14 6d1 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Ralph A. James",
        descoberta: "1958",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Nobel%C3%ADo",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#E0E0E0",
        origemNome: "Em homenagem a Alfred Nobel, inventor da dinamite",
        densidade: "N/A",
        radioatividade: "Sim"
      },
      {
        numero: "103",
        nome: "Laurêncio",
        tipo: "Actinídeo",
        simbolo: "Lr",
        massa: "262",
        configuracao: "[Rn] 5f14 6d1 7s2",
        estado: "Sólido",
        descobridor: "Albert Ghiorso, Glenn T. Seaborg, Ralph A. James",
        descoberta: "1961",
        usos: "Pesquisa científica e fontes de radiação",
        wikipedia: "https://pt.wikipedia.org/wiki/Laur%C3%AAncio",
        niveldeenergia: "7",
        densidadeSTP: "N/A",
        densidadeliquido: "N/A",
        abundanciaUniverso: "0%",
        grupo: "3",
        periodo: "7",
        bloco: "f",
        cor: "#D8D8D8",
        origemNome: "Em homenagem ao cientista Glenn T. Seaborg",
        densidade: "N/A",
        radioatividade: "Sim"
      },
  ];