const temperaturas = [
  {
    numero: "1",
    calorEspecifico: "14.304",
    calorVaporizacao: "0.44936",
    calorFusao: "0.05868",
    pontoFusaoCelsius: "-259.16",
    pontoEbulicaoCelsius: "-252.87",
    pontoFusaoFahrenheit: "-434.49",
    pontoEbulicaoFahrenheit: "-423.17",
    pontoFusaoKelvin: "13.99",
    pontoEbulicaoKelvin: "20.28",
    expansaoTermica: "",
    temperaturaCritica: "-239.96",
    temperaturaTriploponto: "13.8033",
  },
  {
    numero: "2",
    calorEspecifico: "5.193",
    calorVaporizacao: "0.0845",
    calorFusao: "0.0138",
    pontoFusaoCelsius: "-272.2",
    pontoEbulicaoCelsius: "-268.93",
    pontoFusaoFahrenheit: "-457.96",
    pontoEbulicaoFahrenheit: "-452.07",
    pontoFusaoKelvin: "0.95",
    pontoEbulicaoKelvin: "4.22",
    expansaoTermica: "",
    temperaturaCritica: "-267.96",
    temperaturaTriploponto: "2.177",
  },
  {
    numero: "3",
    calorEspecifico: "3.582",
    calorVaporizacao: "147",
    calorFusao: "4.9",
    pontoFusaoCelsius: "180.54",
    pontoEbulicaoCelsius: "1342",
    pontoFusaoFahrenheit: "356.97",
    pontoEbulicaoFahrenheit: "2447.6",
    pontoFusaoKelvin: "453.69",
    pontoEbulicaoKelvin: "1615",
    expansaoTermica: "85",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "4",
    calorEspecifico: "1.825",
    calorVaporizacao: "297",
    calorFusao: "12.2",
    pontoFusaoCelsius: "1287",
    pontoEbulicaoCelsius: "2469",
    pontoFusaoFahrenheit: "2348.6",
    pontoEbulicaoFahrenheit: "4476.2",
    pontoFusaoKelvin: "1560",
    pontoEbulicaoKelvin: "2742",
    expansaoTermica: "11.4",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "5",
    calorEspecifico: "1.026",
    calorVaporizacao: "507",
    calorFusao: "50.2",
    pontoFusaoCelsius: "2076",
    pontoEbulicaoCelsius: "3927",
    pontoFusaoFahrenheit: "3768.8",
    pontoEbulicaoFahrenheit: "7100.6",
    pontoFusaoKelvin: "2349",
    pontoEbulicaoKelvin: "4200",
    expansaoTermica: "6",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "6",
    calorEspecifico: "0.709",
    calorVaporizacao: "710",
    calorFusao: "105",
    pontoFusaoCelsius: "3550",
    pontoEbulicaoCelsius: "4827",
    pontoFusaoFahrenheit: "6422",
    pontoEbulicaoFahrenheit: "8720.6",
    pontoFusaoKelvin: "3823",
    pontoEbulicaoKelvin: "5100",
    expansaoTermica: "1",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "7",
    calorEspecifico: "1.04",
    calorVaporizacao: "2.79",
    calorFusao: "0.72",
    pontoFusaoCelsius: "-210.1",
    pontoEbulicaoCelsius: "-195.8",
    pontoFusaoFahrenheit: "-346.2",
    pontoEbulicaoFahrenheit: "-320.4",
    pontoFusaoKelvin: "63.05",
    pontoEbulicaoKelvin: "77.36",
    expansaoTermica: "",
    temperaturaCritica: "-146.95",
    temperaturaTriploponto: "63.15",
  },
  {
    numero: "8",
    calorEspecifico: "0.918",
    calorVaporizacao: "6.82",
    calorFusao: "0.444",
    pontoFusaoCelsius: "-218.8",
    pontoEbulicaoCelsius: "-183",
    pontoFusaoFahrenheit: "-361.8",
    pontoEbulicaoFahrenheit: "-297.4",
    pontoFusaoKelvin: "54.36",
    pontoEbulicaoKelvin: "90.2",
    expansaoTermica: "",
    temperaturaCritica: "-118.6",
    temperaturaTriploponto: "54.36",
  },
  {
    numero: "9",
    calorEspecifico: "0.824",
    calorVaporizacao: "3.27",
    calorFusao: "0.51",
    pontoFusaoCelsius: "-219.62",
    pontoEbulicaoCelsius: "-188.14",
    pontoFusaoFahrenheit: "-363.32",
    pontoEbulicaoFahrenheit: "-306.65",
    pontoFusaoKelvin: "53.53",
    pontoEbulicaoKelvin: "85.01",
    expansaoTermica: "",
    temperaturaCritica: "-129.0",
    temperaturaTriploponto: "53.48",
  },
  {
    numero: "10",
    calorEspecifico: "1.03",
    calorVaporizacao: "1.75",
    calorFusao: "0.33",
    pontoFusaoCelsius: "-248.59",
    pontoEbulicaoCelsius: "-246.08",
    pontoFusaoFahrenheit: "-415.46",
    pontoEbulicaoFahrenheit: "-410.94",
    pontoFusaoKelvin: "24.56",
    pontoEbulicaoKelvin: "27.07",
    expansaoTermica: "",
    temperaturaCritica: "-228.7",
    temperaturaTriploponto: "24.56",
  },
  {
    numero: "11",
    calorEspecifico: "1.228",
    calorVaporizacao: "97.42",
    calorFusao: "2.6",
    pontoFusaoCelsius: "97.72",
    pontoEbulicaoCelsius: "883",
    pontoFusaoFahrenheit: "207.9",
    pontoEbulicaoFahrenheit: "1621.4",
    pontoFusaoKelvin: "370.87",
    pontoEbulicaoKelvin: "1156",
    expansaoTermica: "71",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "12",
    calorEspecifico: "1.023",
    calorVaporizacao: "128",
    calorFusao: "8.7",
    pontoFusaoCelsius: "650",
    pontoEbulicaoCelsius: "1090",
    pontoFusaoFahrenheit: "1202",
    pontoEbulicaoFahrenheit: "1994",
    pontoFusaoKelvin: "923",
    pontoEbulicaoKelvin: "1363",
    expansaoTermica: "26",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "13",
    calorEspecifico: "0.897",
    calorVaporizacao: "293",
    calorFusao: "10.7",
    pontoFusaoCelsius: "660.3",
    pontoEbulicaoCelsius: "2519",
    pontoFusaoFahrenheit: "1220.5",
    pontoEbulicaoFahrenheit: "4566.2",
    pontoFusaoKelvin: "933.47",
    pontoEbulicaoKelvin: "2792",
    expansaoTermica: "24",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "14",
    calorEspecifico: "0.705",
    calorVaporizacao: "383",
    calorFusao: "50.6",
    pontoFusaoCelsius: "1414",
    pontoEbulicaoCelsius: "2900",
    pontoFusaoFahrenheit: "2577.2",
    pontoEbulicaoFahrenheit: "5252",
    pontoFusaoKelvin: "1687",
    pontoEbulicaoKelvin: "3173",
    expansaoTermica: "2.6",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "15",
    calorEspecifico: "0.769",
    calorVaporizacao: "50.1",
    calorFusao: "0.66",
    pontoFusaoCelsius: "44.15",
    pontoEbulicaoCelsius: "280.5",
    pontoFusaoFahrenheit: "111.47",
    pontoEbulicaoFahrenheit: "536.9",
    pontoFusaoKelvin: "317.3",
    pontoEbulicaoKelvin: "553.7",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "16",
    calorEspecifico: "0.71",
    calorVaporizacao: "9.8",
    calorFusao: "1.73",
    pontoFusaoCelsius: "115.2",
    pontoEbulicaoCelsius: "444.6",
    pontoFusaoFahrenheit: "239.36",
    pontoEbulicaoFahrenheit: "832.28",
    pontoFusaoKelvin: "388.35",
    pontoEbulicaoKelvin: "717.75",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
    {
    numero: "17",
    calorEspecifico: "0.479",
    calorVaporizacao: "10.2",
    calorFusao: "3.26",
    pontoFusaoCelsius: "-101.5",
    pontoEbulicaoCelsius: "-34.04",
    pontoFusaoFahrenheit: "-150.7",
    pontoEbulicaoFahrenheit: "-29.27",
    pontoFusaoKelvin: "171.65",
    pontoEbulicaoKelvin: "239.11",
    expansaoTermica: "",
    temperaturaCritica: "143.9",
    temperaturaTriploponto: "172.31",
  },
  {
    numero: "18",
    calorEspecifico: "0.52",
    calorVaporizacao: "6.5",
    calorFusao: "1.18",
    pontoFusaoCelsius: "-189.4",
    pontoEbulicaoCelsius: "-185.8",
    pontoFusaoFahrenheit: "-308.9",
    pontoEbulicaoFahrenheit: "-302.4",
    pontoFusaoKelvin: "83.8",
    pontoEbulicaoKelvin: "87.3",
    expansaoTermica: "",
    temperaturaCritica: "-122.3",
    temperaturaTriploponto: "83.81",
  },
  {
    numero: "19",
    calorEspecifico: "0.757",
    calorVaporizacao: "76.9",
    calorFusao: "2.33",
    pontoFusaoCelsius: "63.5",
    pontoEbulicaoCelsius: "759",
    pontoFusaoFahrenheit: "146.3",
    pontoEbulicaoFahrenheit: "1398.2",
    pontoFusaoKelvin: "336.65",
    pontoEbulicaoKelvin: "1032.15",
    expansaoTermica: "83",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "20",
    calorEspecifico: "0.647",
    calorVaporizacao: "154",
    calorFusao: "8.54",
    pontoFusaoCelsius: "842",
    pontoEbulicaoCelsius: "1484",
    pontoFusaoFahrenheit: "1547.6",
    pontoEbulicaoFahrenheit: "2703.2",
    pontoFusaoKelvin: "1115",
    pontoEbulicaoKelvin: "1757",
    expansaoTermica: "22.3",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "21",
    calorEspecifico: "0.568",
    calorVaporizacao: "318",
    calorFusao: "16",
    pontoFusaoCelsius: "1541",
    pontoEbulicaoCelsius: "2836",
    pontoFusaoFahrenheit: "2805.8",
    pontoEbulicaoFahrenheit: "5136.8",
    pontoFusaoKelvin: "1814",
    pontoEbulicaoKelvin: "3109",
    expansaoTermica: "10.2",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "22",
    calorEspecifico: "0.523",
    calorVaporizacao: "425",
    calorFusao: "14.15",
    pontoFusaoCelsius: "1668",
    pontoEbulicaoCelsius: "3287",
    pontoFusaoFahrenheit: "3034.4",
    pontoEbulicaoFahrenheit: "5948.6",
    pontoFusaoKelvin: "1941",
    pontoEbulicaoKelvin: "3560",
    expansaoTermica: "8.6",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "23",
    calorEspecifico: "0.489",
    calorVaporizacao: "425",
    calorFusao: "22.8",
    pontoFusaoCelsius: "1910",
    pontoEbulicaoCelsius: "3407",
    pontoFusaoFahrenheit: "3470",
    pontoEbulicaoFahrenheit: "6164.6",
    pontoFusaoKelvin: "2183",
    pontoEbulicaoKelvin: "3680",
    expansaoTermica: "8.4",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "24",
    calorEspecifico: "0.449",
    calorVaporizacao: "344",
    calorFusao: "21",
    pontoFusaoCelsius: "1907",
    pontoEbulicaoCelsius: "2671",
    pontoFusaoFahrenheit: "3464.6",
    pontoEbulicaoFahrenheit: "4840",
    pontoFusaoKelvin: "2180",
    pontoEbulicaoKelvin: "2944",
    expansaoTermica: "6.2",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "25",
    calorEspecifico: "0.479",
    calorVaporizacao: "221",
    calorFusao: "13.2",
    pontoFusaoCelsius: "1246",
    pontoEbulicaoCelsius: "2061",
    pontoFusaoFahrenheit: "2275",
    pontoEbulicaoFahrenheit: "3741.8",
    pontoFusaoKelvin: "1519",
    pontoEbulicaoKelvin: "2334",
    expansaoTermica: "21.7",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "26",
    calorEspecifico: "0.449",
    calorVaporizacao: "340",
    calorFusao: "13.8",
    pontoFusaoCelsius: "1538",
    pontoEbulicaoCelsius: "2862",
    pontoFusaoFahrenheit: "2800.4",
    pontoEbulicaoFahrenheit: "5183.6",
    pontoFusaoKelvin: "1811",
    pontoEbulicaoKelvin: "3135",
    expansaoTermica: "11.8",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "27",
    calorEspecifico: "0.421",
    calorVaporizacao: "375",
    calorFusao: "16.2",
    pontoFusaoCelsius: "1495",
    pontoEbulicaoCelsius: "2927",
    pontoFusaoFahrenheit: "2723",
    pontoEbulicaoFahrenheit: "5300.6",
    pontoFusaoKelvin: "1768",
    pontoEbulicaoKelvin: "3200",
    expansaoTermica: "13",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "28",
    calorEspecifico: "0.444",
    calorVaporizacao: "378",
    calorFusao: "17.5",
    pontoFusaoCelsius: "1455",
    pontoEbulicaoCelsius: "2913",
    pontoFusaoFahrenheit: "2651",
    pontoEbulicaoFahrenheit: "5275.4",
    pontoFusaoKelvin: "1728",
    pontoEbulicaoKelvin: "3186",
    expansaoTermica: "13.4",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "29",
    calorEspecifico: "0.385",
    calorVaporizacao: "300.4",
    calorFusao: "13.05",
    pontoFusaoCelsius: "1084.6",
    pontoEbulicaoCelsius: "2562",
    pontoFusaoFahrenheit: "1984.3",
    pontoEbulicaoFahrenheit: "4643.6",
    pontoFusaoKelvin: "1357.7",
    pontoEbulicaoKelvin: "2835",
    expansaoTermica: "16.5",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "30",
    calorEspecifico: "0.388",
    calorVaporizacao: "115",
    calorFusao: "7.32",
    pontoFusaoCelsius: "419.5",
    pontoEbulicaoCelsius: "907",
    pontoFusaoFahrenheit: "787.1",
    pontoEbulicaoFahrenheit: "1664.6",
    pontoFusaoKelvin: "692.7",
    pontoEbulicaoKelvin: "1180",
    expansaoTermica: "30.2",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "31",
    calorEspecifico: "0.372",
    calorVaporizacao: "256",
    calorFusao: "5.59",
    pontoFusaoCelsius: "29.76",
    pontoEbulicaoCelsius: "2204",
    pontoFusaoFahrenheit: "85.57",
    pontoEbulicaoFahrenheit: "3999.2",
    pontoFusaoKelvin: "302.91",
    pontoEbulicaoKelvin: "2477",
    expansaoTermica: "18.2",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "32",
    calorEspecifico: "0.32",
    calorVaporizacao: "334",
    calorFusao: "36.8",
    pontoFusaoCelsius: "938.3",
    pontoEbulicaoCelsius: "2833",
    pontoFusaoFahrenheit: "1720.9",
    pontoEbulicaoFahrenheit: "5131.4",
    pontoFusaoKelvin: "1211.5",
    pontoEbulicaoKelvin: "3106",
    expansaoTermica: "5.9",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
    {
    numero: "33",
    calorEspecifico: "0.328",
    calorVaporizacao: "34.76",
    calorFusao: "24.44",
    pontoFusaoCelsius: "817",
    pontoEbulicaoCelsius: "614",
    pontoFusaoFahrenheit: "1502.6",
    pontoEbulicaoFahrenheit: "1137.2",
    pontoFusaoKelvin: "1090",
    pontoEbulicaoKelvin: "887",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "34",
    calorEspecifico: "0.321",
    calorVaporizacao: "26.99",
    calorFusao: "5.4",
    pontoFusaoCelsius: "221",
    pontoEbulicaoCelsius: "685",
    pontoFusaoFahrenheit: "429.8",
    pontoEbulicaoFahrenheit: "1265",
    pontoFusaoKelvin: "494",
    pontoEbulicaoKelvin: "958",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "35",
    calorEspecifico: "0.473",
    calorVaporizacao: "15.4",
    calorFusao: "10.57",
    pontoFusaoCelsius: "-7.2",
    pontoEbulicaoCelsius: "59",
    pontoFusaoFahrenheit: "19",
    pontoEbulicaoFahrenheit: "138.2",
    pontoFusaoKelvin: "266",
    pontoEbulicaoKelvin: "332",
    expansaoTermica: "",
    temperaturaCritica: "320",
    temperaturaTriploponto: "",
  },
  {
    numero: "36",
    calorEspecifico: "0.248",
    calorVaporizacao: "9.05",
    calorFusao: "1.64",
    pontoFusaoCelsius: "-157.4",
    pontoEbulicaoCelsius: "-153.4",
    pontoFusaoFahrenheit: "-251.3",
    pontoEbulicaoFahrenheit: "-244.1",
    pontoFusaoKelvin: "115.8",
    pontoEbulicaoKelvin: "119.8",
    expansaoTermica: "",
    temperaturaCritica: "-63.7",
    temperaturaTriploponto: "115.78",
  },
  {
    numero: "37",
    calorEspecifico: "0.363",
    calorVaporizacao: "72.2",
    calorFusao: "2.39",
    pontoFusaoCelsius: "39.3",
    pontoEbulicaoCelsius: "688",
    pontoFusaoFahrenheit: "102.7",
    pontoEbulicaoFahrenheit: "1270.4",
    pontoFusaoKelvin: "312.5",
    pontoEbulicaoKelvin: "961",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "38",
    calorEspecifico: "0.301",
    calorVaporizacao: "137",
    calorFusao: "8.3",
    pontoFusaoCelsius: "769",
    pontoEbulicaoCelsius: "1384",
    pontoFusaoFahrenheit: "1416.2",
    pontoEbulicaoFahrenheit: "2523.2",
    pontoFusaoKelvin: "1042",
    pontoEbulicaoKelvin: "1657",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "39",
    calorEspecifico: "0.298",
    calorVaporizacao: "380",
    calorFusao: "15.3",
    pontoFusaoCelsius: "1526",
    pontoEbulicaoCelsius: "3338",
    pontoFusaoFahrenheit: "2778.8",
    pontoEbulicaoFahrenheit: "6040.4",
    pontoFusaoKelvin: "1799",
    pontoEbulicaoKelvin: "3611",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "40",
    calorEspecifico: "0.278",
    calorVaporizacao: "591",
    calorFusao: "21",
    pontoFusaoCelsius: "1855",
    pontoEbulicaoCelsius: "4409",
    pontoFusaoFahrenheit: "3371",
    pontoEbulicaoFahrenheit: "7968.2",
    pontoFusaoKelvin: "2128",
    pontoEbulicaoKelvin: "4682",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "41",
    calorEspecifico: "0.265",
    calorVaporizacao: "689",
    calorFusao: "27.2",
    pontoFusaoCelsius: "2477",
    pontoEbulicaoCelsius: "4744",
    pontoFusaoFahrenheit: "4490.6",
    pontoEbulicaoFahrenheit: "8571.2",
    pontoFusaoKelvin: "2750",
    pontoEbulicaoKelvin: "5017",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "42",
    calorEspecifico: "0.251",
    calorVaporizacao: "598",
    calorFusao: "33",
    pontoFusaoCelsius: "2623",
    pontoEbulicaoCelsius: "4639",
    pontoFusaoFahrenheit: "4753.4",
    pontoEbulicaoFahrenheit: "8382.2",
    pontoFusaoKelvin: "2896",
    pontoEbulicaoKelvin: "4912",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "43",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "2200",
    pontoEbulicaoCelsius: "4877",
    pontoFusaoFahrenheit: "3992",
    pontoEbulicaoFahrenheit: "8810.6",
    pontoFusaoKelvin: "2473",
    pontoEbulicaoKelvin: "5150",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "44",
    calorEspecifico: "0.238",
    calorVaporizacao: "580",
    calorFusao: "24",
    pontoFusaoCelsius: "2334",
    pontoEbulicaoCelsius: "4150",
    pontoFusaoFahrenheit: "4233.2",
    pontoEbulicaoFahrenheit: "7502",
    pontoFusaoKelvin: "2607",
    pontoEbulicaoKelvin: "4423",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "45",
    calorEspecifico: "0.238",
    calorVaporizacao: "580",
    calorFusao: "26.74",
    pontoFusaoCelsius: "1964",
    pontoEbulicaoCelsius: "3727",
    pontoFusaoFahrenheit: "3567.2",
    pontoEbulicaoFahrenheit: "6740.6",
    pontoFusaoKelvin: "2237",
    pontoEbulicaoKelvin: "4000",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "46",
    calorEspecifico: "0.244",
    calorVaporizacao: "370",
    calorFusao: "15.5",
    pontoFusaoCelsius: "1554.9",
    pontoEbulicaoCelsius: "2963",
    pontoFusaoFahrenheit: "2830.8",
    pontoEbulicaoFahrenheit: "5365.4",
    pontoFusaoKelvin: "1828",
    pontoEbulicaoKelvin: "3236",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "47",
    calorEspecifico: "0.235",
    calorVaporizacao: "254",
    calorFusao: "11.3",
    pontoFusaoCelsius: "961.8",
    pontoEbulicaoCelsius: "2162",
    pontoFusaoFahrenheit: "1763.2",
    pontoEbulicaoFahrenheit: "3923.6",
    pontoFusaoKelvin: "1234",
    pontoEbulicaoKelvin: "2435",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "48",
    calorEspecifico: "0.232",
    calorVaporizacao: "99.87",
    calorFusao: "6.11",
    pontoFusaoCelsius: "321",
    pontoEbulicaoCelsius: "767",
    pontoFusaoFahrenheit: "609.8",
    pontoEbulicaoFahrenheit: "1412.6",
    pontoFusaoKelvin: "594",
    pontoEbulicaoKelvin: "1040",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "49",
    calorEspecifico: "0.233",
    calorVaporizacao: "230",
    calorFusao: "3.26",
    pontoFusaoCelsius: "156.6",
    pontoEbulicaoCelsius: "2080",
    pontoFusaoFahrenheit: "313.9",
    pontoEbulicaoFahrenheit: "3776",
    pontoFusaoKelvin: "429.8",
    pontoEbulicaoKelvin: "2353",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "50",
    calorEspecifico: "0.228",
    calorVaporizacao: "296",
    calorFusao: "7.03",
    pontoFusaoCelsius: "231.9",
    pontoEbulicaoCelsius: "2602",
    pontoFusaoFahrenheit: "449.4",
    pontoEbulicaoFahrenheit: "4715.6",
    pontoFusaoKelvin: "505",
    pontoEbulicaoKelvin: "2875",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "51",
    calorEspecifico: "0.207",
    calorVaporizacao: "195",
    calorFusao: "11.72",
    pontoFusaoCelsius: "630.6",
    pontoEbulicaoCelsius: "1587",
    pontoFusaoFahrenheit: "1167",
    pontoEbulicaoFahrenheit: "2888.6",
    pontoFusaoKelvin: "903.7",
    pontoEbulicaoKelvin: "1860",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "52",
    calorEspecifico: "0.202",
    calorVaporizacao: "45",
    calorFusao: "17.5",
    pontoFusaoCelsius: "449.5",
    pontoEbulicaoCelsius: "988",
    pontoFusaoFahrenheit: "841.1",
    pontoEbulicaoFahrenheit: "1810.4",
    pontoFusaoKelvin: "723",
    pontoEbulicaoKelvin: "1261",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "53",
    calorEspecifico: "0.214",
    calorVaporizacao: "41.6",
    calorFusao: "15.52",
    pontoFusaoCelsius: "113.7",
    pontoEbulicaoCelsius: "184.3",
    pontoFusaoFahrenheit: "236.7",
    pontoEbulicaoFahrenheit: "363.7",
    pontoFusaoKelvin: "386.9",
    pontoEbulicaoKelvin: "457.5",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "54",
    calorEspecifico: "0.158",
    calorVaporizacao: "12.64",
    calorFusao: "3.8",
    pontoFusaoCelsius: "-111.8",
    pontoEbulicaoCelsius: "-108.1",
    pontoFusaoFahrenheit: "-169.2",
    pontoEbulicaoFahrenheit: "-162.6",
    pontoFusaoKelvin: "161.3",
    pontoEbulicaoKelvin: "165.1",
    expansaoTermica: "",
    temperaturaCritica: "-16.6",
    temperaturaTriploponto: "161.4",
  },
  {
    numero: "55",
    calorEspecifico: "0.242",
    calorVaporizacao: "67.74",
    calorFusao: "2.09",
    pontoFusaoCelsius: "28.4",
    pontoEbulicaoCelsius: "671",
    pontoFusaoFahrenheit: "83.1",
    pontoEbulicaoFahrenheit: "1239.8",
    pontoFusaoKelvin: "301.6",
    pontoEbulicaoKelvin: "944.2",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
  {
    numero: "56",
    calorEspecifico: "0.204",
    calorVaporizacao: "140",
    calorFusao: "8",
    pontoFusaoCelsius: "727",
    pontoEbulicaoCelsius: "1897",
    pontoFusaoFahrenheit: "1340.6",
    pontoEbulicaoFahrenheit: "3446.6",
    pontoFusaoKelvin: "1000",
    pontoEbulicaoKelvin: "2170",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: "",
  },
    {
    numero: "72",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "25.5",
    pontoFusaoCelsius: "2233",
    pontoEbulicaoCelsius: "4602",
    pontoFusaoFahrenheit: "4051.4",
    pontoEbulicaoFahrenheit: "8315.6",
    pontoFusaoKelvin: "2506.15",
    pontoEbulicaoKelvin: "4875.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "73",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "36",
    pontoFusaoCelsius: "3017",
    pontoEbulicaoCelsius: "5458",
    pontoFusaoFahrenheit: "5462.6",
    pontoEbulicaoFahrenheit: "9856.4",
    pontoFusaoKelvin: "3290.15",
    pontoEbulicaoKelvin: "5731.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "74",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "3422",
    pontoEbulicaoCelsius: "5555",
    pontoFusaoFahrenheit: "6191.6",
    pontoEbulicaoFahrenheit: "10031",
    pontoFusaoKelvin: "3695.15",
    pontoEbulicaoKelvin: "5828.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "75",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "3186",
    pontoEbulicaoCelsius: "5596",
    pontoFusaoFahrenheit: "5766.8",
    pontoEbulicaoFahrenheit: "10164.8",
    pontoFusaoKelvin: "3459.15",
    pontoEbulicaoKelvin: "5869.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "76",
    calorEspecifico: "",
    calorVaporizacao: "627.6",
    calorFusao: "31.8",
    pontoFusaoCelsius: "3033",
    pontoEbulicaoCelsius: "5008",
    pontoFusaoFahrenheit: "5491.4",
    pontoEbulicaoFahrenheit: "9046.4",
    pontoFusaoKelvin: "3306.15",
    pontoEbulicaoKelvin: "5281.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "77",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "2410",
    pontoEbulicaoCelsius: "4130",
    pontoFusaoFahrenheit: "4370",
    pontoEbulicaoFahrenheit: "7466",
    pontoFusaoKelvin: "2683.15",
    pontoEbulicaoKelvin: "4403.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "78",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "1768.2",
    pontoEbulicaoCelsius: "3825",
    pontoFusaoFahrenheit: "3214.8",
    pontoEbulicaoFahrenheit: "6917",
    pontoFusaoKelvin: "2041.35",
    pontoEbulicaoKelvin: "4098.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "79",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "1064.18",
    pontoEbulicaoCelsius: "2856",
    pontoFusaoFahrenheit: "1947.5",
    pontoEbulicaoFahrenheit: "5172.8",
    pontoFusaoKelvin: "1337.33",
    pontoEbulicaoKelvin: "3129.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "80",
    calorEspecifico: "",
    calorVaporizacao: "59.11",
    calorFusao: "2.29",
    pontoFusaoCelsius: "-38.83",
    pontoEbulicaoCelsius: "356.73",
    pontoFusaoFahrenheit: "-37.89",
    pontoEbulicaoFahrenheit: "674.11",
    pontoFusaoKelvin: "234.32",
    pontoEbulicaoKelvin: "629.88",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "81",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "304",
    pontoEbulicaoCelsius: "1473",
    pontoFusaoFahrenheit: "579.2",
    pontoEbulicaoFahrenheit: "2683.4",
    pontoFusaoKelvin: "577.15",
    pontoEbulicaoKelvin: "1746.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "82",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "4.77",
    pontoFusaoCelsius: "327.46",
    pontoEbulicaoCelsius: "1749",
    pontoFusaoFahrenheit: "621.43",
    pontoEbulicaoFahrenheit: "3180.2",
    pontoFusaoKelvin: "600.61",
    pontoEbulicaoKelvin: "2022.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "83",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "271.4",
    pontoEbulicaoCelsius: "1564",
    pontoFusaoFahrenheit: "520.52",
    pontoEbulicaoFahrenheit: "2847.2",
    pontoFusaoKelvin: "544.55",
    pontoEbulicaoKelvin: "1837.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "84",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "254",
    pontoEbulicaoCelsius: "962",
    pontoFusaoFahrenheit: "489.2",
    pontoEbulicaoFahrenheit: "1763.6",
    pontoFusaoKelvin: "527.15",
    pontoEbulicaoKelvin: "1235.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "85",
    calorEspecifico: "",
    calorVaporizacao: "",
    calorFusao: "",
    pontoFusaoCelsius: "302",
    pontoEbulicaoCelsius: "337",
    pontoFusaoFahrenheit: "575.6",
    pontoEbulicaoFahrenheit: "638.6",
    pontoFusaoKelvin: "575.15",
    pontoEbulicaoKelvin: "610.15",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "86",
    calorEspecifico: "",
    calorVaporizacao: "16.4",
    calorFusao: "2.89",
    pontoFusaoCelsius: "-71",
    pontoEbulicaoCelsius: "-61.8",
    pontoFusaoFahrenheit: "-95.8",
    pontoEbulicaoFahrenheit: "-79.2",
    pontoFusaoKelvin: "202.15",
    pontoEbulicaoKelvin: "211.35",
    expansaoTermica: "",
    temperaturaCritica: "104",
    temperaturaTriploponto: ""
  },
    {
    numero: "87",
    calorEspecifico: "",
    calorVaporizacao: "65",
    calorFusao: "2",
    pontoFusaoCelsius: "27",
    pontoEbulicaoCelsius: "677",
    pontoFusaoFahrenheit: "80.6",
    pontoEbulicaoFahrenheit: "1250.6",
    pontoFusaoKelvin: "300",
    pontoEbulicaoKelvin: "950",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "88",
    calorEspecifico: "",
    calorVaporizacao: "113",
    calorFusao: "8.5",
    pontoFusaoCelsius: "700",
    pontoEbulicaoCelsius: "1737",
    pontoFusaoFahrenheit: "1292",
    pontoEbulicaoFahrenheit: "3158.6",
    pontoFusaoKelvin: "973",
    pontoEbulicaoKelvin: "2010",
    expansaoTermica: "",
    temperaturaCritica: "",
    temperaturaTriploponto: ""
  },
  {
    numero: "104",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "105",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "106",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "107",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "108",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "109",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "110",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "111",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "112",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "113",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "114",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "115",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "116",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "117",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "118",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "N/A",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "N/A",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "N/A",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
    {
    numero: "57",
    calorEspecifico: "0.19",
    calorVaporizacao: "414",
    calorFusao: "6.2",
    pontoFusaoCelsius: "920",
    pontoEbulicaoCelsius: "3464",
    pontoFusaoFahrenheit: "1688",
    pontoEbulicaoFahrenheit: "6267",
    pontoFusaoKelvin: "1193",
    pontoEbulicaoKelvin: "3737",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "58",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "798",
    pontoEbulicaoCelsius: "3426",
    pontoFusaoFahrenheit: "1468",
    pontoEbulicaoFahrenheit: "6199",
    pontoFusaoKelvin: "1071",
    pontoEbulicaoKelvin: "3699",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "59",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "931",
    pontoEbulicaoCelsius: "3520",
    pontoFusaoFahrenheit: "1708",
    pontoEbulicaoFahrenheit: "6368",
    pontoFusaoKelvin: "1204",
    pontoEbulicaoKelvin: "3793",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "60",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1021",
    pontoEbulicaoCelsius: "3074",
    pontoFusaoFahrenheit: "1870",
    pontoEbulicaoFahrenheit: "5565",
    pontoFusaoKelvin: "1294",
    pontoEbulicaoKelvin: "3347",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "61",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1042",
    pontoEbulicaoCelsius: "3000",
    pontoFusaoFahrenheit: "1908",
    pontoEbulicaoFahrenheit: "5432",
    pontoFusaoKelvin: "1315",
    pontoEbulicaoKelvin: "3273",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "62",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1072",
    pontoEbulicaoCelsius: "1794",
    pontoFusaoFahrenheit: "1962",
    pontoEbulicaoFahrenheit: "3261",
    pontoFusaoKelvin: "1345",
    pontoEbulicaoKelvin: "2067",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "63",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "822",
    pontoEbulicaoCelsius: "1597",
    pontoFusaoFahrenheit: "1512",
    pontoEbulicaoFahrenheit: "2907",
    pontoFusaoKelvin: "1095",
    pontoEbulicaoKelvin: "1870",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "64",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1050",
    pontoEbulicaoCelsius: "3273",
    pontoFusaoFahrenheit: "1922",
    pontoEbulicaoFahrenheit: "5923",
    pontoFusaoKelvin: "1323",
    pontoEbulicaoKelvin: "3546",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "65",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1092",
    pontoEbulicaoCelsius: "3130",
    pontoFusaoFahrenheit: "1998",
    pontoEbulicaoFahrenheit: "5666",
    pontoFusaoKelvin: "1365",
    pontoEbulicaoKelvin: "3403",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "66",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1412",
    pontoEbulicaoCelsius: "2567",
    pontoFusaoFahrenheit: "2574",
    pontoEbulicaoFahrenheit: "4653",
    pontoFusaoKelvin: "1685",
    pontoEbulicaoKelvin: "2840",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "67",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1529",
    pontoEbulicaoCelsius: "2870",
    pontoFusaoFahrenheit: "2784",
    pontoEbulicaoFahrenheit: "5198",
    pontoFusaoKelvin: "1802",
    pontoEbulicaoKelvin: "3143",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "68",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1526",
    pontoEbulicaoCelsius: "2510",
    pontoFusaoFahrenheit: "2779",
    pontoEbulicaoFahrenheit: "4550",
    pontoFusaoKelvin: "1799",
    pontoEbulicaoKelvin: "2783",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "69",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1545",
    pontoEbulicaoCelsius: "1727",
    pontoFusaoFahrenheit: "2813",
    pontoEbulicaoFahrenheit: "3141",
    pontoFusaoKelvin: "1818",
    pontoEbulicaoKelvin: "2000",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "70",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "824",
    pontoEbulicaoCelsius: "1196",
    pontoFusaoFahrenheit: "1515",
    pontoEbulicaoFahrenheit: "2185",
    pontoFusaoKelvin: "1097",
    pontoEbulicaoKelvin: "1469",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
  {
    numero: "71",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1652",
    pontoEbulicaoCelsius: "3402",
    pontoFusaoFahrenheit: "3006",
    pontoEbulicaoFahrenheit: "6156",
    pontoFusaoKelvin: "1925",
    pontoEbulicaoKelvin: "3675",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A"
  },
    {
    numero: "89",
    calorEspecifico: "0.12",
    calorVaporizacao: "N/A",
    calorFusao: "14.1",
    pontoFusaoCelsius: "1050",
    pontoEbulicaoCelsius: "3200",
    pontoFusaoFahrenheit: "1922",
    pontoEbulicaoFahrenheit: "5792",
    pontoFusaoKelvin: "1323",
    pontoEbulicaoKelvin: "3473",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "90",
    calorEspecifico: "0.113",
    calorVaporizacao: "425",
    calorFusao: "16",
    pontoFusaoCelsius: "1750",
    pontoEbulicaoCelsius: "4788",
    pontoFusaoFahrenheit: "3182",
    pontoEbulicaoFahrenheit: "8650",
    pontoFusaoKelvin: "2023",
    pontoEbulicaoKelvin: "5061",
    expansaoTermica: "11.0",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "91",
    calorEspecifico: "0.12",
    calorVaporizacao: "481",
    calorFusao: "20",
    pontoFusaoCelsius: "1572",
    pontoEbulicaoCelsius: "4000",
    pontoFusaoFahrenheit: "2862",
    pontoEbulicaoFahrenheit: "7232",
    pontoFusaoKelvin: "1845",
    pontoEbulicaoKelvin: "4273",
    expansaoTermica: "9.9",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "92",
    calorEspecifico: "0.116",
    calorVaporizacao: "417",
    calorFusao: "14",
    pontoFusaoCelsius: "1132",
    pontoEbulicaoCelsius: "4131",
    pontoFusaoFahrenheit: "2070",
    pontoEbulicaoFahrenheit: "7468",
    pontoFusaoKelvin: "1405",
    pontoEbulicaoKelvin: "4404",
    expansaoTermica: "13.9",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "93",
    calorEspecifico: "0.116",
    calorVaporizacao: "689.9",
    calorFusao: "27.2",
    pontoFusaoCelsius: "640",
    pontoEbulicaoCelsius: "3902",
    pontoFusaoFahrenheit: "1184",
    pontoEbulicaoFahrenheit: "7056",
    pontoFusaoKelvin: "913",
    pontoEbulicaoKelvin: "4175",
    expansaoTermica: "13.7",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "94",
    calorEspecifico: "0.12",
    calorVaporizacao: "325",
    calorFusao: "N/A",
    pontoFusaoCelsius: "639.4",
    pontoEbulicaoCelsius: "3232",
    pontoFusaoFahrenheit: "1182.9",
    pontoEbulicaoFahrenheit: "5849.6",
    pontoFusaoKelvin: "912.6",
    pontoEbulicaoKelvin: "3505",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "95",
    calorEspecifico: "0.1",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1176",
    pontoEbulicaoCelsius: "2607",
    pontoFusaoFahrenheit: "2149",
    pontoEbulicaoFahrenheit: "4725",
    pontoFusaoKelvin: "1449",
    pontoEbulicaoKelvin: "2880",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "96",
    calorEspecifico: "0.12",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1340",
    pontoEbulicaoCelsius: "3110",
    pontoFusaoFahrenheit: "2444",
    pontoEbulicaoFahrenheit: "5630",
    pontoFusaoKelvin: "1613",
    pontoEbulicaoKelvin: "3383",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "97",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "986",
    pontoEbulicaoCelsius: "2627",
    pontoFusaoFahrenheit: "1807",
    pontoEbulicaoFahrenheit: "4761",
    pontoFusaoKelvin: "1259",
    pontoEbulicaoKelvin: "2900",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "98",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1173",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "2143",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1446",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "99",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "860",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "1580",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1133",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "100",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "827",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "1521",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1100",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "101",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "827",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "1521",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1100",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "102",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "830",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "1526",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1103",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  },
  {
    numero: "103",
    calorEspecifico: "N/A",
    calorVaporizacao: "N/A",
    calorFusao: "N/A",
    pontoFusaoCelsius: "1627",
    pontoEbulicaoCelsius: "N/A",
    pontoFusaoFahrenheit: "2961",
    pontoEbulicaoFahrenheit: "N/A",
    pontoFusaoKelvin: "1900",
    pontoEbulicaoKelvin: "N/A",
    expansaoTermica: "N/A",
    temperaturaCritica: "N/A",
    temperaturaTriploponto: "N/A",
  }
];